unsigned char *PhoneticTable[][2] = {
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "º¸¦Õ¬|Ââ»ç", (unsigned char *) "-3" },
	{ (unsigned char *) "¤G¶L", (unsigned char *) "-4" },
	{ (unsigned char *) "¨à¦Ó", (unsigned char *) "-6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¼Ú¼Ş¿^ÅÃ", (unsigned char *) ". " },
	{ (unsigned char *) "°¸¹Ã½¢ÃÂ", (unsigned char *) ".3" },
	{ (unsigned char *) "¾¾", (unsigned char *) ".4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¦w±g®ò¿Ú»Ï¾bÄO", (unsigned char *) "0 " },
	{ (unsigned char *) "­Í", (unsigned char *) "03" },
	{ (unsigned char *) "®×µÚÅf©¤«ö·t", (unsigned char *) "04" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "±YÁ^", (unsigned char *) "1/ " }, 
	{ (unsigned char *) "ÂÛ°n", (unsigned char *) "1/4" },
	{ (unsigned char *) "¬Ç", (unsigned char *) "1/6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "§æ·h´³½I¯ë¹{¯Z", (unsigned char *) "10 " },
	{ (unsigned char *) "ªOª©¯ê¶z¨ÁÁó", (unsigned char *) "103" },
	{ (unsigned char *) "¦ñ¿ì¥b©r§ê©ÕÃ¤²Ì", (unsigned char *) "104" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤K¥z§a¤Ú¥¶®Ã¬Í¯¹ªİ", (unsigned char *) "18 " },
	{ (unsigned char *) "§â¹v", (unsigned char *) "183" },
	{ (unsigned char *) "ª¨ÅòÅô½}ÅQ", (unsigned char *) "184" },
	{ (unsigned char *) "©Ş¶[¹Y", (unsigned char *) "186" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
#ifdef  WIN32
	{ (unsigned char *) "¨ÕÂ\¦ÊÄü", (unsigned char *) "193" },
#else
	{ (unsigned char *) "¨ÕÂ\\¦ÊÄü", (unsigned char *) "193" },
#endif  /*WIN32*/
	{ (unsigned char *) "«ô±Ñ", (unsigned char *) "194" },
	{ (unsigned char *) "¥Õ", (unsigned char *) "196" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "À°³Ä±õ¨¹", (unsigned char *) "1; " },
	{ (unsigned char *) "º]¸j»H", (unsigned char *) "1;3" },
	{ (unsigned char *) "´Î½S°FÁ½Âé", (unsigned char *) "1;4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "­é¼·¬Á²ÚµÔ", (unsigned char *) "1i " },
	{ (unsigned char *) "¶_", (unsigned char *) "1i3" },
	{ (unsigned char *) "­½¼½À¼ÀĞÃ°", (unsigned char *) "1i4" },
	{ (unsigned char *) "§BÁ¡«k³Õ©­·i¬fªy´ñºä²ä½³»K²í²ò¹`»é", (unsigned char *) "1i6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "­÷®·¸É", (unsigned char *) "1j3" },
	{ (unsigned char *) "¤£³¡¨B§G°ğ¥¬©ÆÃ¯¹Z", (unsigned char *) "1j4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¥]­M­c½Ç", (unsigned char *) "1l " },
	{ (unsigned char *) "«O³ùÄ_¸¶½È¹¡", (unsigned char *) "1l3" },
#ifdef  WIN32
	{ (unsigned char *) "³ø©ê¼ÉÃz°\¹^ÅáÀj§S", (unsigned char *) "1l4" },
#else
	{ (unsigned char *) "³ø©ê¼ÉÃz°\\¹^ÅáÀj§S", (unsigned char *) "1l4" },
#endif  /*WIN32*/
	{ (unsigned char *) "¹r", (unsigned char *) "1l6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¨õ´d´®ªM¬×¸O", (unsigned char *) "1o " },
	{ (unsigned char *) "¥_", (unsigned char *) "1o3" },
	{ (unsigned char *) "³Q­¿³Æ¨©½ú­IÁu§¸®¯¾ÎµH¯V»_ªõ¾X", (unsigned char *) "1o4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¹à", (unsigned char *) "sp4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "©b", (unsigned char *) "1p " },
	{ (unsigned char *) "¥»¯c­f", (unsigned char *) "1p3" },
	{ (unsigned char *) "²Â", (unsigned char *) "1p4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "åxÅ¾", (unsigned char *) "1u, " },
	{ (unsigned char *) "Ã§", (unsigned char *) "1u,3" },
	{ (unsigned char *) "¹û", (unsigned char *) "1u,4" },
	{ (unsigned char *) "§O", (unsigned char *) "1u,6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "§L¦B", (unsigned char *) "1u/ " },
	{ (unsigned char *) "¤ş¬`¬±ªÃ¸[»Ğ»æ", (unsigned char *) "1u/3" },
	{ (unsigned char *) "¨Ã¨Ö¦}´¬¯f", (unsigned char *) "1u/4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "Ãä¯¢½s½¿Ã@", (unsigned char *) "1u0 " },
	{ (unsigned char *) "°Ğ«ó¶S", (unsigned char *) "1u03" },
	{ (unsigned char *) "«KÅÜ¤Ë¥¯¨XÄ|ÅG¿ë¹M¨¼", (unsigned char *) "1u04" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¹G", (unsigned char *) "1u " },
	{ (unsigned char *) "¤ñ©¼µ§»À¤P§­¨]", (unsigned char *) "1u3" },
	{ (unsigned char *) "¥²±Í²¦¾ÀÁ×Âz³¬¹ô§È¹ú´]´pÀÅ·ô¸DºÑ¿{½ªÁ£»tÃÎ¶G¶NÂŞ¹@¹c°¡¹Í±A­Ú", (unsigned char *) "1u4" },
	{ (unsigned char *) "»ó", (unsigned char *) "1u6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¼Ğ³C½¨Ãğ", (unsigned char *) "1ul " },
	{ (unsigned char *) "ªí¿ö±D", (unsigned char *) "1ul3" },
	{ (unsigned char *) "ÅÀ", (unsigned char *) "1ul4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¾ª±lÂbÀØÃxÄ}ÁÇ»«", (unsigned char *) "1up " },
	{ (unsigned char *) "ÂlÂÁÆK", (unsigned char *) "1up4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "°Â³£", (unsigned char *) "2. " },
	{ (unsigned char *) "°B°~¤æ§İªU", (unsigned char *) "2.3" },
	{ (unsigned char *) "¨§³rÄu²è°«", (unsigned char *) "2.4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "µn¿O", (unsigned char *) "2/ " },
	{ (unsigned char *) "µ¥", (unsigned char *) "2/3" },
	{ (unsigned char *) "¹¹¼jÀüÁEÃŞ¾H", (unsigned char *) "2/4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤¦¾á³æÏà¯Ô", (unsigned char *) "20 " },
	{ (unsigned char *) "Áx¼Â¯n", (unsigned char *) "203" },
	{ (unsigned char *) "¦ı°è°Ü¼ª¥¹´á²H¿F³J½Ï", (unsigned char *) "204" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "·f¿Ê", (unsigned char *) "28 " },
	{ (unsigned char *) "¥´", (unsigned char *) "283" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "©Íµª¹F»ŞÅ¶½D", (unsigned char *) "286" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "§b", (unsigned char *) "29 " },
	{ (unsigned char *) "¤ï¶e", (unsigned char *) "293" },
	{ (unsigned char *) "¥N¶U¤j©§±a«İ«åÀ¹¬p¬Å³U­¤ÂL", (unsigned char *) "294" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "·í»ı¾´ÃËÅL", (unsigned char *) "2; " },
	{ (unsigned char *) "¾×ÄÒÀÉÆm", (unsigned char *) "2;3" },
	{ (unsigned char *) "Àú¿º", (unsigned char *) "2;4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¹Ê·ş", (unsigned char *) "2j " },
	{ (unsigned char *) "½ä°ô¸@¿w", (unsigned char *) "2j3" },
	{ (unsigned char *) "«×´ç¨{§ªÁá§ùÅû", (unsigned char *) "2j4" },
	{ (unsigned char *) "¬rÃpÂpÃ|Ã}¿WÅªÅêÆu", (unsigned char *) "2j6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "©NªFÃ]¥V", (unsigned char *) "2j/ " },
	{ (unsigned char *) "À´¸³", (unsigned char *) "2j/3" },
	{ (unsigned char *) "°Ê­á«ğ´É¬}¯Û", (unsigned char *) "2j/4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ºİ­B", (unsigned char *) "2j0 " },
	{ (unsigned char *) "µu", (unsigned char *) "2j03" },
	{ (unsigned char *) "¬qÂ_½vÁë", (unsigned char *) "2j04" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¦h", (unsigned char *) "2ji " },
	{ (unsigned char *) "¦·¸ú", (unsigned char *) "2ji3" },
	{ (unsigned char *) "¨ï©F¼Z´k²ë¸ö¿â", (unsigned char *) "2ji4" },
	{ (unsigned char *) "¹ÜÅM", (unsigned char *) "2ji6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "°ï", (unsigned char *) "2jo " },
	{ (unsigned char *) "§I¹ï¸P¶¤", (unsigned char *) "2jo4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "´°¼[±¬ÃÛ", (unsigned char *) "2jp " },
	{ (unsigned char *) "¬ÚÄ»", (unsigned char *) "2jp3" },
	{ (unsigned char *) "¾·¨P¿L¬Ş¹P¶w¹y", (unsigned char *) "2jp4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¼w±o", (unsigned char *) "2k6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤M¥o", (unsigned char *) "2l " },
	{ (unsigned char *) "¾É®q·oÃ«", (unsigned char *) "2l3" },
	{ (unsigned char *) "¨ì­Ë±¥µs½_ÁĞ¹D", (unsigned char *) "2l4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "§Cºw", (unsigned char *) "2u " },
	{ (unsigned char *) "©³ªó©è¶C¬»¯¡", (unsigned char *) "2u3" },
	{ (unsigned char *) "¦a®X«Ò§Ì´Ğªº¿Í²Ä½l¸¦»¼", (unsigned char *) "2u4" },
	{ (unsigned char *) "¹¿¹Ş¼Äº°¨f²Ã»C²ı­}Ãé", (unsigned char *) "2u6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¯R", (unsigned char *) "2u, " },
	{ (unsigned char *) "¶^³ã·ŞÅ|ºĞµ»µÀ½º¿Ò­¡", (unsigned char *) "2u,6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "Åq·¿ÅöÄA", (unsigned char *) "2u0 " },
	{ (unsigned char *) "¨åÂI¸K", (unsigned char *) "2u03" },
	{ (unsigned char *) "¹q©±¦ú¹Ô³ş±}·µ¾ı¬¿¨l¹fÀQ", (unsigned char *) "2u04" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¥á", (unsigned char *) "2u. " },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤B¤±¥m¨n°v", (unsigned char *) "2u/ " },
	{ (unsigned char *) "­ª³»¹©", (unsigned char *) "2u/3" },
	{ (unsigned char *) "©w­q¿õ", (unsigned char *) "2u/4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ÀJ­ä¤N¥p±n¸M¶IÄK", (unsigned char *) "2ul " },
	{ (unsigned char *) "¦Q¤İ±¼³¨", (unsigned char *) "2ul4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤§¥g¤äªK±÷¥Äª¾¯­Â´ªÏ­O¯×ªÛ»j°¦", (unsigned char *) "5 " },
	{ (unsigned char *) "¥u«¤§}«ü¦®¤î¬ç¯Èªé³k", (unsigned char *) "53" },
	{ (unsigned char *) "§Ó¨î«Ï¼m¼°´¼ªvª|º¢ª¥²©µi¯´¸X²¿½o¸m¦Ü­Pµí»s»xÅ®¸ş¹n", (unsigned char *) "54" },
	{ (unsigned char *) "ÂY´Ó´Şª½Â¾½è°õ«¿Å­­È", (unsigned char *) "56" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "©P°ç¦{¬wµ°¦à¶g", (unsigned char *) "5. " },
	{ (unsigned char *) "©ª¨y¬ô", (unsigned char *) "5.3" },
	{ (unsigned char *) "©z«`©G±Ş½K", (unsigned char *) "5.4" },
	{ (unsigned char *) "©o¶b", (unsigned char *) "5.6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "±W©º¼x©Ã±Ãª§²uÄp¸Cºå»]½Ø¿ş", (unsigned char *) "5/ " },
	{ (unsigned char *) "¬@¾ã", (unsigned char *) "5/3" },
	{ (unsigned char *) "¥¿¬F´V¯gµıÃÒ¾G", (unsigned char *) "5/4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ÀÖªgÂ¤¸âÄ¸ÀL", (unsigned char *) "50 " },
	{ (unsigned char *) "®i¹ñ±Ù·øÁÓ", (unsigned char *) "503" },
	{ (unsigned char *) "¦û¥e¾Ô¼È´Ì´ï¯¸ºìÅÙÅ¸", (unsigned char *) "504" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "³å´í", (unsigned char *) "58 " },
	{ (unsigned char *) "¯w¯¤", (unsigned char *) "583" },
#ifdef  WIN32
	{ (unsigned char *) "¥E¦\·cº^¬]¬µ³K¶B©Q", (unsigned char *) "584" },
#else
	{ (unsigned char *) "¥E¦\\·cº^¬]¬µ³K¶B©Q", (unsigned char *) "584" },
#endif  /*WIN32*/
	{ (unsigned char *) "¤ã¥¾¹h", (unsigned char *) "586" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ºKÂN", (unsigned char *) "59 " },
	{ (unsigned char *) "¯¶", (unsigned char *) "593" },
	{ (unsigned char *) "¶Å¹ë", (unsigned char *) "594" },
	{ (unsigned char *) "¦v", (unsigned char *) "596" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "±i¹ü¼Ìºsº¼¼ı³¹Á­", (unsigned char *) "5; " },
	{ (unsigned char *) "´xº¦", (unsigned char *) "5;3" },
	{ (unsigned char *) "¤V¥M±b¹ó§ú¿`µÈ½ã»Ù", (unsigned char *) "5;4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¨Ü¦¶®è²¹¯üµï¸İ½Ñ½Ş¸ù»Ë¯]", (unsigned char *) "5j " },
	{ (unsigned char *) "¥DÅñ©Ö²ZµNÆf¶J", (unsigned char *) "5j3" },
	{ (unsigned char *) "ª`¦î¦í§UªV¬W¯¬ºæ­RµÛ³EµùÅ±¾n", (unsigned char *) "5j3" },
	{ (unsigned char *) "¥ºÀë¦ËªÇµ®¿vÄ½³v", (unsigned char *) "5j6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤¤©¾¬Ø²×°JÁéÄÁ", (unsigned char *) "5j/ " },
	{ (unsigned char *) "­à¶ïºØ¸~¿æ", (unsigned char *) "5j/3" },
	{ (unsigned char *) "¥òµF²³­«", (unsigned char *) "5j/4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "±M¿jÃF", (unsigned char *) "5j0 " },
	{ (unsigned char *) "ÄÚÂà", (unsigned char *) "5j03" },
	{ (unsigned char *) "ÁÈ¹¶¼¶½f", (unsigned char *) "5j04" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "§ì", (unsigned char *) "5j8 " },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "§©¼Î²ø¸Ë", (unsigned char *) "5j; " },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "§§¼²ª¬", (unsigned char *) "5j;4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "®»®à´Í²g", (unsigned char *) "5ji " },
	{ (unsigned char *) "¨ô°Ö©åÀÂ¬H¿BÀŞ¨`µZ­_°uÅN", (unsigned char *) "5ji6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "´Õ°lÀ@«A", (unsigned char *) "5jo " },
	{ (unsigned char *) "¼Y´mºóÂØ", (unsigned char *) "5jo4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ªÒ½ÎÏş", (unsigned char *) "5jp " },
	{ (unsigned char *) "­ã·Ç", (unsigned char *) "5jp3" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "Á±¾B", (unsigned char *) "5k " },
	{ (unsigned char *) "ªÌ½ê", (unsigned char *) "5k3" },
	{ (unsigned char *) "®ı½©³oÅÂ", (unsigned char *) "5k4" },
	{ (unsigned char *) "­õÄà§éºP¸½Á·ÂÖ", (unsigned char *) "5k6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "©Û¬L´Â°x", (unsigned char *) "5l " },
	{ (unsigned char *) "§äªh¤ö", (unsigned char *) "5l3" },
	{ (unsigned char *) "¥ü¥l¬··Ó¸n»F¶@»¯", (unsigned char *) "5l4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "°»·r·©ºd¬ÃºÂ¯u¯zºÕ½e¿²­s°w", (unsigned char *) "5p " },
	{ (unsigned char *) "ªE¯l¿¦¶E", (unsigned char *) "5p3" },
	{ (unsigned char *) "®¶®Ó»¬Âí°}¾_¾}×ò®W", (unsigned char *) "5p4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ªü°Ú", (unsigned char *) "8 " },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "«s«u­ü®J®Á", (unsigned char *) "9 " },
	{ (unsigned char *) "¸GÄ§ÆG", (unsigned char *) "93" },
	{ (unsigned char *) "¾¼·RÀÇÀõÃª¦ã", (unsigned char *) "94" },
	{ (unsigned char *) "±º½J", (unsigned char *) "96" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "»ê", (unsigned char *) "; " },
	{ (unsigned char *) "¯s", (unsigned char *) ";4" },
	{ (unsigned char *) "©ù", (unsigned char *) ";6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¬Y", (unsigned char *) "a.3" },
	{ (unsigned char *) "¦È²¶Á[¿Ñ", (unsigned char *) "a.6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "²r»S»g¿ø", (unsigned char *) "a/3" },
	{ (unsigned char *) "¹Ú©s", (unsigned char *) "a/4" },
	{ (unsigned char *) "ÃjÂaÂcÀÛ¿_·ùÃ©µŞ»X­j", (unsigned char *) "a/6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "º¡®^", (unsigned char *) "a03" },
	{ (unsigned char *) "ºC¹÷°Òº©Ág½¯Ãî", (unsigned char *) "a04" },
	{ (unsigned char *) "ÆZÄCÅÁÂÚ¿f", (unsigned char *) "a06" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¶ı¶ÜÀ¨", (unsigned char *) "a8 " },
	{ (unsigned char *) "º¿½X¿Â°¨", (unsigned char *) "a83" },
	{ (unsigned char *) "½|", (unsigned char *) "a84" },
	{ (unsigned char *) "¹À·ò³Â»ò", (unsigned char *) "a86" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "½æÁÚ³Á", (unsigned char *) "a94" },
	{ (unsigned char *) "¶R", (unsigned char *) "a93" },
	{ (unsigned char *) "®IÅµ", (unsigned char *) "a96" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "²õÁ¯", (unsigned char *) "a;3" },
	{ (unsigned char *) "¦£ª]ª¼¨~¯í", (unsigned char *) "a;6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ºN", (unsigned char *) "ai " },
	{ (unsigned char *) "©Ù", (unsigned char *) "ai3" },
#ifdef  WIN32
	{ (unsigned char *) "¥½Àq¾¥¹æª\ªjºz¯°¯ß­[²ö¸ç­¯ÅZ", (unsigned char *) "ai4" },
#else
	{ (unsigned char *) "¥½Àq¾¥¹æª\\ªjºz¯°¯ß­[²ö¸ç­¯ÅZ", (unsigned char *) "ai4" },
#endif  /*WIN32*/
	{ (unsigned char *) "¼Ò¼¯¼±¿iÁU½¤Ä¨ÂÓÅ]", (unsigned char *) "ai6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¥À©i©æ¨d¯a", (unsigned char *) "aj3" },
	{ (unsigned char *) "¤ì¥Ø¶Ò¹Ó¹õ¼Ç¨Nªª·ü¿p­`¼}", (unsigned char *) "aj4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¿ß", (unsigned char *) "al " },
	{ (unsigned char *) "¥f­gª}", (unsigned char *) "al3" },
	{ (unsigned char *) "¶T­Z«_´UÀ·¬ş»ª·è", (unsigned char *) "al4" },
	{ (unsigned char *) "¤ò¥Ù­TÁã»ì", (unsigned char *) "al6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¨C¬üÁâ", (unsigned char *) "ao3" },
	{ (unsigned char *) "©f´A´Kªz°L¾y¬N", (unsigned char *) "ao4" },
	{ (unsigned char *) "¨S´CªT±ö·°µD·Ñª´¬Ü²ù¾`Åğ", (unsigned char *) "ao6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "´eÂV¿T", (unsigned char *) "ap " },
	{ (unsigned char *) "­Ì±¿ªù", (unsigned char *) "ap6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "«}½N", (unsigned char *) "au " },
	{ (unsigned char *) "¦Ì«Ú®Å", (unsigned char *) "au3" },
	{ (unsigned char *) "»e±K¾­¨Qªc¯¦¯µ¦Í³VÁÄ", (unsigned char *) "au4" },
	{ (unsigned char *) "À±ÄjÁSÁ¼ÃûÂG°g", (unsigned char *) "au6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "«§ªË", (unsigned char *) "au, " },
	{ (unsigned char *) "·ÀÁN½°", (unsigned char *) "au,4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ÂÕ", (unsigned char *) "au.4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "©R", (unsigned char *) "au/4" },
#ifdef  WIN32
	{ (unsigned char *) "º\¦W©ú½P¯ú¿Á¹U»Ê»ï­ß", (unsigned char *) "au/6" },
#else
	{ (unsigned char *) "º\\¦W©ú½P¯ú¿Á¹U»Ê»ï­ß", (unsigned char *) "au/6" },
#endif  /*WIN32*/
	{ (unsigned char *) "", (unsigned char *) "" },
#ifdef  WIN32
	{ (unsigned char *) "§K«j°Á°Ã®Y¨\µB½q", (unsigned char *) "au03" },
#else
	{ (unsigned char *) "§K«j°Á°Ã®Y¨\\µB½q", (unsigned char *) "au03" },
#endif  /*WIN32*/
	{ (unsigned char *) "­±ÄÑ", (unsigned char *) "au04" },
	{ (unsigned char *) "´Ö¯vºø", (unsigned char *) "au06" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ªWªH´ù¬à¬í½zÂÆÂä", (unsigned char *) "aul3" },
	{ (unsigned char *) "§®¼q", (unsigned char *) "aul4" },
	{ (unsigned char *) "´yºË­]", (unsigned char *) "aul6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "±Ó·]¼§©×µC¿I¥×¶{»Ôª{", (unsigned char *) "aup3" },
	{ (unsigned char *) "¥Á©¢", (unsigned char *) "aup6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤é", (unsigned char *) "b4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¦×", (unsigned char *) "b.4" },
	{ (unsigned char *) "¬X´|¿äÂı", (unsigned char *) "b.6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¥µ", (unsigned char *) "b/ " },
	{ (unsigned char *) "¤´", (unsigned char *) "b/6" },
	{ (unsigned char *) "", (unsigned char *) "" },
#ifdef  WIN32
	{ (unsigned char *) "¬V­\¥T", (unsigned char *) "b03" },
#else
	{ (unsigned char *) "¬V­\\¥T", (unsigned char *) "b03" },
#endif
	{ (unsigned char *) "¾wµM¿U", (unsigned char *) "b06" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ÄWÄ[Äc", (unsigned char *) "b;3" },
	{ (unsigned char *) "Åı", (unsigned char *) "b;4" },
	{ (unsigned char *) "Å{Å¡", (unsigned char *) "b;6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤¾", (unsigned char *) "bj/3" },
	{ (unsigned char *) "®eÀ¯¦¥º_ºa·»º²µ³¯ñ»T¿ÄÂè", (unsigned char *) "bj/6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¨Å¦¼", (unsigned char *) "bj3" },
	{ (unsigned char *) "¤J¿È°d", (unsigned char *) "bj4" },
	{ (unsigned char *) "¦p¾§À}À©Àá¯øÂwÄ¯", (unsigned char *) "bj6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "­Y°´®zÅd¿x", (unsigned char *) "bji4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "³n¨¿", (unsigned char *) "bj03" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¿¶", (unsigned char *) "bjo3" },
	{ (unsigned char *) "·çºÍ¾U", (unsigned char *) "bjo4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¼í¶|", (unsigned char *) "bjp4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "·S", (unsigned char *) "bk3" },
	{ (unsigned char *) "¼ö", (unsigned char *) "bk4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "Â¶", (unsigned char *) "bl4" },
	{ (unsigned char *) "ÂZ", (unsigned char *) "bl3" },
	{ (unsigned char *) "ÂÌÄÇ¼c", (unsigned char *) "bl6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "§Ô¸Z¯ö", (unsigned char *) "bp3" },
	{ (unsigned char *) "¥ô»{¥Q¤b§³¬÷°M°b¶´¶¹", (unsigned char *) "bp4" },
	{ (unsigned char *) "¤H¤¯¤Ğ", (unsigned char *) "bp6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "§q", (unsigned char *) "c.3" },
	{ (unsigned char *) "­Ô«p¦Z³û«á°mÆM", (unsigned char *) "c.4" },
	{ (unsigned char *) "«J³ïµU½j", (unsigned char *) "c.6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¦ë­ó", (unsigned char *) "c/ " },
	{ (unsigned char *) "¾î«í®ì¿Å", (unsigned char *) "c/6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¶oÂM", (unsigned char *) "c0 " },
	{ (unsigned char *) "³Û¨u", (unsigned char *) "c03" },
	{ (unsigned char *) "®«¾Ñ®Â¾Ù§ò¦½º~Ãv²k¿«¾ZÀX", (unsigned char *) "c04" },
	{ (unsigned char *) "¨ç§t´H²[Áú", (unsigned char *) "c06" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "«¢", (unsigned char *) "c8 " },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "®ü", (unsigned char *) "c93" },
	{ (unsigned char *) "¥è¶Ù®óÀb®`", (unsigned char *) "c94" },
	{ (unsigned char *) "«ÄÀe", (unsigned char *) "c96" },
	{ (unsigned char *) "", (unsigned char *) "" },
#ifdef  WIN32
	{ (unsigned char *) "¨Y§\ªC¯è", (unsigned char *) "c;6" },
#else
	{ (unsigned char *) "¨Y§\\ªC¯è", (unsigned char *) "c;6" },
#endif  /*WIN32*/
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¥G©I©¿±«", (unsigned char *) "cj " },
	{ (unsigned char *) "ªêµ[âq°ä", (unsigned char *) "cj3" },
	{ (unsigned char *) "§z­J´ò³ı©·±Øª°·ä¸¬½¹ÄGÃ[½k", (unsigned char *) "cj6" },
	{ (unsigned char *) "¤¬¤á±¯¨[º­²}Å@", (unsigned char *) "cj4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "«¡¯MÁ©ÅF", (unsigned char *) "cj/ " },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "Ài", (unsigned char *) "cj/4" },
	{ (unsigned char *) "§»¥°ªl¬x¬õ­i°R¶£ÂE", (unsigned char *) "cj/6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "Åw", (unsigned char *) "cj0 " },
	{ (unsigned char *) "½w", (unsigned char *) "cj03" },
	{ (unsigned char *) "¤Û³ê´«µA·ØºÈ¸æ±w", (unsigned char *) "cj04" },
	{ (unsigned char *) "ÁÙ¾È®Ù¬§Àô¿JÁì", (unsigned char *) "cj06" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ªá¼M", (unsigned char *) "cj8 " },
	{ (unsigned char *) "µØ·Æ¦E·âÃÏ", (unsigned char *) "cj86" },
	{ (unsigned char *) "¹º¤Æ¾ìµe¸Ü", (unsigned char *) "cj84" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "Ãa", (unsigned char *) "cj94" },
	{ (unsigned char *) "Ãh«Şºi²a½ï", (unsigned char *) "cj96" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¯î·W¨w", (unsigned char *) "cj; " },
	{ (unsigned char *) "ÁÀ·E«é®Ì", (unsigned char *) "cj;3" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "´qµG·×¿X¬ÓÁD½hÂ®ÃA½À¹N¶ª¶À°Ä´a", (unsigned char *) "cj;6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ÀÃÀâÀòº×Ã¬ÁÅ³fÀN©Î´b", (unsigned char *) "cji4" },
	{ (unsigned char *) "¥ë¹Ù¤õ", (unsigned char *) "cji3" },
	{ (unsigned char *) "¬¡", (unsigned char *) "cji6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¦ÇÀ²«ì´§·u¸Ù½÷¾£", (unsigned char *) "cjo " },
	{ (unsigned char *) "®¬·´Àì¦ä­k»£", (unsigned char *) "cjo3" },
	{ (unsigned char *) "¶×¥c³ñ±k·J¼z±â·|ÀíÂ©Ã¸¿·¿Ğ¸ì´f", (unsigned char *) "cjo4" },
	{ (unsigned char *) "¯õµî°j¦^", (unsigned char *) "cjo6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "©ü±B¸§", (unsigned char *) "cjp " },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "»îÀ_", (unsigned char *) "cjp6" },
	{ (unsigned char *) "²V´ı", (unsigned char *) "cjp4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¨ş³Ü¶F", (unsigned char *) "ck " },
	{ (unsigned char *) "¶P·{²ü»®Åb", (unsigned char *) "ck4" },
	{ (unsigned char *) "¦ó¨ğ¦X©M¬T®Öªe²U²°¯r¥İ¬ø½Å¸è»×»ÒÂó", (unsigned char *) "ck6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¦n°q", (unsigned char *) "cl3" },
	{ (unsigned char *) "©şµq¯E¯Ó¸¹ÂîÅV¹RÑ®æP", (unsigned char *) "cl4" },
	{ (unsigned char *) "»¨²@¶çÀzÀ¢ÀÚÄ®", (unsigned char *) "cl6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¶Â¼K", (unsigned char *) "co " },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "«Ü¬½", (unsigned char *) "cp3" },
	{ (unsigned char *) "«ë", (unsigned char *) "cp4" },
	{ (unsigned char *) "²ª", (unsigned char *) "cp6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤f", (unsigned char *) "d.3" },
	{ (unsigned char *) "¥n±F¦©³§çM", (unsigned char *) "d.4" },
	{ (unsigned char *) "", (unsigned char *) "" },
#ifdef  WIN32
	{ (unsigned char *) "§|Ãô¨Â", (unsigned char *) "d/ " },
#else
	{ (unsigned char *) "§|Ãô¨Â", (unsigned char *) "d/ " },
#endif  /*WIN32*/
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¥Z°É³ô·`", (unsigned char *) "d0 " },
	{ (unsigned char *) "¨Ô§¢®rÂe¬å", (unsigned char *) "d03" },
	{ (unsigned char *) "¬İÀı", (unsigned char *) "d04" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "©@", (unsigned char *) "d8 " },
	{ (unsigned char *) "¥d³Ø", (unsigned char *) "d83" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¶}´{", (unsigned char *) "d9 " },
	{ (unsigned char *) "³Í³Ï·_·¢", (unsigned char *) "d93" },
	{ (unsigned char *) "´n´t·Z", (unsigned char *) "d94" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "±dºBÁR", (unsigned char *) "d; " },
	{ (unsigned char *) "§Ü¤®¥êª¡", (unsigned char *) "d;4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
#ifdef  WIN32
	{ (unsigned char *) "­ú¬\¸]¾u", (unsigned char *) "dj " },
#else
	{ (unsigned char *) "­ú¬\\¸]¾u", (unsigned char *) "dj " },
#endif  /*WIN32*/
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ªÅ­Ã±S¸Q", (unsigned char *) "dj/ " },
	{ (unsigned char *) "¤Õ®£", (unsigned char *) "dj/3" },
	{ (unsigned char *) "±±", (unsigned char *) "dj/4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¼eÆb", (unsigned char *) "dj0 " },
	{ (unsigned char *) "´Ú", (unsigned char *) "dj03" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "­W·±", (unsigned char *) "dj3" },
	{ (unsigned char *) "®w¿Ç»Å", (unsigned char *) "dj4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¸Ø¦j", (unsigned char *) "dj8 " },
	{ (unsigned char *) "«±", (unsigned char *) "dj83" },
	{ (unsigned char *) "¸ó¯ãéÎ", (unsigned char *) "dj84" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "§Ö»û¼D¶ôÀÌ¸_Áz", (unsigned char *) "dj94" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¦J¨ñµ¨", (unsigned char *) "dj; " },
	{ (unsigned char *) "ªpÂRÃm®Ø²µÄq", (unsigned char *) "dj;4" },
	{ (unsigned char *) "¨g»¥", (unsigned char *) "dj;6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¬A¹øÂXµòÁï", (unsigned char *) "dj84" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¿s²¯Á«", (unsigned char *) "djo " },
	{ (unsigned char *) "³È", (unsigned char *) "djo3" },
#ifdef  WIN32
	{ (unsigned char *) "·\¹¼³ç¼ìÂ±ÃJ", (unsigned char *) "djo4" },
#else
	{ (unsigned char *) "·\\¹¼³ç¼ìÂ±ÃJ", (unsigned char *) "dho4" },
#endif  /*WIN32*/
	{ (unsigned char *) "ÄÜ«¶´}ºÌ¸ª¶f»í", (unsigned char *) "djo6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "©[±X©øµOÀC¹¦", (unsigned char *) "djp " },
	{ (unsigned char *) "®¹±î¸i", (unsigned char *) "djp3" },
	{ (unsigned char *) "§xµt", (unsigned char *) "djp4" },
	{ (unsigned char *) "", (unsigned char *) "" },
#ifdef  WIN32
	{ (unsigned char *) "¨è¬_´ÊÁû½O½W¬ì¸\¸^­V½Á¶a", (unsigned char *) "dk " },
#else
	{ (unsigned char *) "¨è¬_´ÊÁû½O½W¬ì¸\\¸^­V½Á¶a", (unsigned char *) "dk " },
#endif  /*WIN32*/
	{ (unsigned char *) "¥i©V´÷", (unsigned char *) "dk3" },
	{ (unsigned char *) "§J«g¶ß«È«ñ·Â½y½ÒÃN", (unsigned char *) "dk4" },
	{ (unsigned char *) "«y´ß", (unsigned char *) "dk6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¦Ò«ş¯N", (unsigned char *) "dl3" },
	{ (unsigned char *) "¾aº¹¾R", (unsigned char *) "dl4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ªÖ°Ù¾ÁÀµ", (unsigned char *) "dp3" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤Ä·¾¹_", (unsigned char *) "e. " },
	{ (unsigned char *) "ª¯¬e­e", (unsigned char *) "e.3" },
	{ (unsigned char *) "°÷«¯¶ü·pºc¸áÁÊ", (unsigned char *) "d.4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "©°§ó¸eÃ¼¯Ñ½é", (unsigned char *) "e/ " },
	{ (unsigned char *) "®C®G±ğ¯Õ", (unsigned char *) "e/3" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "°®©XÀª¤z§ı¥Ì¯i¬ñ¨x¬a", (unsigned char *) "e0 " },
	{ (unsigned char *) "·P´±±ì¾ñµz»°", (unsigned char *) "e03" },
	{ (unsigned char *) "·Fºm²hÆB", (unsigned char *) "e04" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¹Ç", (unsigned char *) "e83" },
	{ (unsigned char *) "§¼", (unsigned char *) "e84" },
	{ (unsigned char *) "ªî", (unsigned char *) "e86" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¸Ó«²", (unsigned char *) "e9 " },
	{ (unsigned char *) "§ï", (unsigned char *) "e93" },
#ifdef  WIN32
	{ (unsigned char *) "¤¢·§µ@»\¶t", (unsigned char *) "e94" },
#else
	{ (unsigned char *) "¤¢·§µ@»\\¶t", (unsigned char *) "e94" },
#endif  /*WIN32*/
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "±^­è©£¦ª§şºõ¬û¨z³ª¿û", (unsigned char *) "e; " },
	{ (unsigned char *) "´ä", (unsigned char *) "e;3" },
	{ (unsigned char *) "ºb", (unsigned char *) "e;4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¦ô©B©h©tªfµİ³G¶d¹WÀlØâàµ", (unsigned char *) "ej " },
#ifdef  WIN32
	{ (unsigned char *) "¥j¬ºÂ¢½\¯ËªÑÅÛµş¨¦ÁÔ°©¹ª", (unsigned char *) "ej3" },
#else
	{ (unsigned char *) "¥j¬ºÂ¢½\\¯ËªÑÅÛµş¨¦ÁÔ°©¹ª", (unsigned char *) "ej3" },
#endif  /*WIN32*/
	{ (unsigned char *) "¹µ©T¬GÀD¶±ÅU", (unsigned char *) "ej4" },
	{ (unsigned char *) "", (unsigned char *) "" },
#ifdef  WIN32
	{ (unsigned char *) "¨Ñ¤½¥\®c¤u¤}®¥§ğªĞ°G°`", (unsigned char *) "ej/ " },
#else
	{ (unsigned char *) "¨Ñ¤½¥\\®c¤u¤}®¥§ğªĞ°G°`", (unsigned char *) "ej/ " },
#endif  /*WIN32*/
	{ (unsigned char *) "¤{«ı¨E¾d", (unsigned char *) "ej/3" },
	{ (unsigned char *) "¦@°^", (unsigned char *) "ej/4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "Æ[­¾©x´ÃÃöÅ`", (unsigned char *) "ej0 " },
	{ (unsigned char *) "ºŞµ_À]", (unsigned char *) "ej03" },
	{ (unsigned char *) "«aºDÅø³eÆ|¿dÄé", (unsigned char *) "dj04" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¨í©K¥ÊµÁ½½¾h", (unsigned char *) "ej8 " },
	{ (unsigned char *) "¹è", (unsigned char *) "ej83" },
	{ (unsigned char *) "¨ö¬E±¾»o", (unsigned char *) "ej84" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¨Ä", (unsigned char *) "ej9 " },
	{ (unsigned char *) "©ä¬b", (unsigned char *) "ej93" },
	{ (unsigned char *) "©Ç", (unsigned char *) "ej94" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¥ú¬©¯Ö", (unsigned char *) "ej; " },
	{ (unsigned char *) "Âx¼s", (unsigned char *) "ej;3" },
	{ (unsigned char *) "³}", (unsigned char *) "ej;4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "³úÁ´³¢Áç", (unsigned char *) "eji " },
	{ (unsigned char *) "ªG¼Í²t»q", (unsigned char *) "eji3" },
	{ (unsigned char *) "¹L", (unsigned char *) "eji4" },
	{ (unsigned char *) "°ê¹öºQ", (unsigned char *) "eji6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¦c¯^ºÀ¬Ô³W»ÓÂDÀtÂk", (unsigned char *) "ejo " },
	{ (unsigned char *) "°­´¾¬Ñ¸Ş­y", (unsigned char *) "ejo3" },
	{ (unsigned char *) "¶Q®ÛÂd¸÷", (unsigned char *) "ejo4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ºu³OÃX¾@", (unsigned char *) "ejp3" },
	{ (unsigned char *) "´Ò", (unsigned char *) "ejp4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "­ô³Î¤àÀÁºqª¸¯ŞÂF", (unsigned char *) "ek " },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "­Ó¦Uºç»Ì", (unsigned char *) "ek4" },
	{ (unsigned char *) "­²¹j¾¿®æ»J¸¯¾gµğ­¨»ÕÀfÂğ", (unsigned char *) "ek6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "°ª¸A»I¯o¿t¿|¯Ì", (unsigned char *) "el " },
	{ (unsigned char *) "·dªXº`½Z¿¥", (unsigned char *) "el3" },
	{ (unsigned char *) "§i»¢", (unsigned char *) "el4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "®Ú¸ò", (unsigned char *) "ep " },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¥å¦áÓ£", (unsigned char *) "ep4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¯Ê", (unsigned char *) "fm, " },
	{ (unsigned char *) "½T«o©ÄºeÁğÂö³¶ÄN", (unsigned char *) "fm,4" },
	{ (unsigned char *) "¿a", (unsigned char *) "fm,6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ªÆÃ£½a", (unsigned char *) "fm/6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤ü¬Êª¶ãe", (unsigned char *) "fm03" },
	{ (unsigned char *) "ÄU¨é", (unsigned char *) "fm04" },
	{ (unsigned char *) "¥ş¨Ş®±Åv¬u²¬¯ş»l¸à½ô»Í", (unsigned char *) "fm06" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "°Ï©}¹ò¦±Â£¯£³IµñÁÍÂßÅX", (unsigned char *) "fm " },
	{ (unsigned char *) "¨ú", (unsigned char *) "fm3" },
	{ (unsigned char *) "¥h½ì", (unsigned char *) "fm4" },
	{ (unsigned char *) "´ë§WÀóÅüÄT°ùÆT", (unsigned char *) "fm6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¸s¸È", (unsigned char *) "fmp6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤C©d±~¼¡±­¬m´Ï´Û²Yº£µÖ", (unsigned char *) "fu " },
	{ (unsigned char *) "¤^±Ò§ûºö°Z°_", (unsigned char *) "fu3" },
	{ (unsigned char *) "¬ä¥ø¾¹«´¾Í±óª_¿l½r°W¨´®ğ¨T", (unsigned char *) "fu,4" },
	{ (unsigned char *) "¨ä§¦©_§Á±TºX´Á´Ñª[²NµXµa²¥ªÂ¬è¬é¯ÏÂÀ°NÀBÃMÅ_ÄQ»ô", (unsigned char *) "fu6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¥B", (unsigned char *) "fu,3" },
	{ (unsigned char *) "¤Á©c´g®²ÅÑÁæ", (unsigned char *) "fu,4" },
	{ (unsigned char *) "¦÷­X", (unsigned char *) "fu,6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¥C¬î³LªôÂşÄÏ", (unsigned char *) "fu. " },
	{ (unsigned char *) "¥}²A±ü¨Dªs²y¸Ê­©", (unsigned char *) "fu.6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¶É­ë²B²M»f»´«CÄJ", (unsigned char *) "fu/ " },
	{ (unsigned char *) "½Ğ³¼", (unsigned char *) "fu/3" },
	{ (unsigned char *) "¼y¿kÁj", (unsigned char *) "fu/4" },
	{ (unsigned char *) "±¡Àº´¸ÀÒ", (unsigned char *) "fu/6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¥a¤d´O·^ºS²oÃ±ÅÒÁ¾¾E¹]¦éÆHÄÊ", (unsigned char *) "fu0 " },
	{ (unsigned char *) "Äş»º²L", (unsigned char *) "fu03" },
	{ (unsigned char *) "¤í­Å¹ÕºpÁd", (unsigned char *) "fu04" },
	{ (unsigned char *) "«e¼çºã°@¶x¹X¿úÀr", (unsigned char *) "fu06" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "Õt", (unsigned char *) "fu8 " },
	{ (unsigned char *) "ÒÕ", (unsigned char *) "" },
	{ (unsigned char *) "«ê¬¢", (unsigned char *) "fu84" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ºjªÊµÄÂòÃò", (unsigned char *) "fu; " },
	{ (unsigned char *) "·mÁfîu", (unsigned char *) "fu;3" },
	{ (unsigned char *) "¶æ", (unsigned char *) "fu;4" },
	{ (unsigned char *) "±j¾Ê©ÏÀÎÀğÁ¥", (unsigned char *) "fu;6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ºVÃßÁê", (unsigned char *) "ful " },
	{ (unsigned char *) "¥©®¨´s", (unsigned char *) "ful3" },
	{ (unsigned char *) "®k¼ÀÂ¬Â¼»¦ÀT«N", (unsigned char *) "ful4" },
	{ (unsigned char *) "¹´³ì¼¬¾ö¾ôÁ@Ã×", (unsigned char *) "ful6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¿Ë«I¼k´Ü", (unsigned char *) "fup " },
	{ (unsigned char *) "¹ì", (unsigned char *) "fup3" },
	{ (unsigned char *) "¼Ã¨G", (unsigned char *) "fup4" },
	{ (unsigned char *) "¶Ô¾²¾àµ^¸V¯³ªà", (unsigned char *) "fup6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¦¬", (unsigned char *) "g. " },
	{ (unsigned char *) "¦u¤â­º", (unsigned char *) "g.3" },
	{ (unsigned char *) "¨ü°â¹Ø±Â¬¼Ã~½Gºş", (unsigned char *) "g.4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¥Í¤Éª@¬¹µc°¥Án²Æ", (unsigned char *) "g/ " },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "³Ó³Ñ²±¸tÁË", (unsigned char *) "g/4" },
	{ (unsigned char *) "Ã·", (unsigned char *) "g/6" },
	{ (unsigned char *) "", (unsigned char *) "" },
#ifdef  WIN32
	{ (unsigned char *) "¤s§R©kºU§ü¼è¬ÀÃ»ªß­m¶\Áh­Q", (unsigned char *) "g0 " },
#else
	{ (unsigned char *) "¤s§R©kºU§ü¼è¬ÀÃ»ªß­m¶\\Áh­Q", (unsigned char *) "g0 " },
#endif  /*WIN32*/
	{ (unsigned char *) "°{°¢", (unsigned char *) "g03" },
	{ (unsigned char *) "µ½®°¾Õ¦Âº´ª·Âµ¿¯°SÄºÅë", (unsigned char *) "g04" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¥¢¸Ö¤r«Í¬I·ÃÀã·àªë½¾®v", (unsigned char *) "g " },
	{ (unsigned char *) "¨Ï¥v©l«Ë¥Ú¨¨¾p", (unsigned char *) "g3" },
	{ (unsigned char *) "¥Ü¥@¬O¨Æ¦¡¥K¨Í«Ç¥«¶Õ¶İ¾½¤h¼]·I«î«ø¬U¤ó¸b¯çµø¸Õ»}ÃÑ¸ı¾AÄÀ¹¢³u", (unsigned char *) "g4" },
	{ (unsigned char *) "¤Q¹ê¬B®É¥Û»k­¹", (unsigned char *) "g6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "±ş¨F¬â¯½²ï¸ÆÃT", (unsigned char *) "g8 " },
	{ (unsigned char *) "¶Ì", (unsigned char *) "g83" },
	{ (unsigned char *) "·ÙÀK", (unsigned char *) "g84" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¿z", (unsigned char *) "g9 " },
	{ (unsigned char *) "®ÍÅÎ", (unsigned char *) "g94" },
	{ (unsigned char *) "»ë", (unsigned char *) "g93" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "°Ó¶Ë¼Ü»nÂÒ", (unsigned char *) "g; " },
	{ (unsigned char *) "®Î", (unsigned char *) "g;3" },
	{ (unsigned char *) "¤W©|", (unsigned char *) "g;4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "®Ñ§ç®Ş¿é¼Ï®í²¨ÀÏµÎ½­", (unsigned char *) "gj " },
	{ (unsigned char *) "´»¸pÁ¦ÃÅ¸¾¶Á¹«Äİ", (unsigned char *) "gj3" },
	{ (unsigned char *) "­z¹Ö±f®¤¦§¼ÆÀÆ§ô¾ğº¤³N½İ°¿", (unsigned char *) "gj4" },
	{ (unsigned char *) "¼ô¨û¹Ñ±E²QµàÅ«", (unsigned char *) "gj6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¬C®ê­¬", (unsigned char *) "gj0 " },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¨ê", (unsigned char *) "gj8 " },
	{ (unsigned char *) "­A", (unsigned char *) "gj84" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "°IºL", (unsigned char *) "gj9 " },
	{ (unsigned char *) "¥Ï", (unsigned char *) "gj93" },
	{ (unsigned char *) "«ÓÁ¬", (unsigned char *) "gj94" },
	{ (unsigned char *) "", (unsigned char *) "" },
#ifdef  WIN32
	{ (unsigned char *) "ÂùÄ\Á÷", (unsigned char *) "gj; " },
#else
	{ (unsigned char *) "ÂùÄ\\Á÷", (unsigned char *) "gj; " },
#endif  /*WIN32*/
	{ (unsigned char *) "²n¹×", (unsigned char *) "gj;3" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ºÓ¦q®ÒÃ{Åà", (unsigned char *) "gji4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤ô", (unsigned char *) "gjo3" },
	{ (unsigned char *) "»¡ºÎµ|ÎÕ", (unsigned char *) "gjo " },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "½Ö", (unsigned char *) "go6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "§m", (unsigned char *) "gjp3" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¶¶ÀşµÏ", (unsigned char *) "gjp4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "°ø»­", (unsigned char *) "gk " },
	{ (unsigned char *) "±Ë", (unsigned char *) "gk3" },
	{ (unsigned char *) "³]ªÀ®gÄá¾ù¯AªÙ³jÅe", (unsigned char *) "gk4" },
	{ (unsigned char *) "¤°¦Ş³D", (unsigned char *) "gk6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "®´±é¿Nµy", (unsigned char *) "gl " },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "­ï¤Ö²Ğªò", (unsigned char *) "gl4" },
	{ (unsigned char *) "¤c¨@¨¢»à", (unsigned char *) "gl6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¦ù©D²`¥Ó¯~²Ô¨­", (unsigned char *) "gp " },
	{ (unsigned char *) "¼f«{ÂT¨HÂn", (unsigned char *) "gp3" },
	{ (unsigned char *) "·Vº¯¬Æ²éµÇ¸Â", (unsigned char *) "gp4" },
	{ (unsigned char *) "¯«", (unsigned char *) "gp6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¦¹", (unsigned char *) "h3" },
	{ (unsigned char *) "¦¸¨ë", (unsigned char *) "h4" },
	{ (unsigned char *) "²«·O²¡ºÏ¯¨»Û¯ıµüÃã", (unsigned char *) "h6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "´¿¼h", (unsigned char *) "h/6" },
	{ (unsigned char *) "", (unsigned char *) "" },
#ifdef  WIN32
	{ (unsigned char *) "À\°Ñ", (unsigned char *) "h0 " },
#else
	{ (unsigned char *) "À\\°Ñ", (unsigned char *) "h0 " },
#endif  /*WIN32*/
	{ (unsigned char *) "ºG", (unsigned char *) "h03" },
	{ (unsigned char *) "ÀéÀö", (unsigned char *) "h04" },
	{ (unsigned char *) "ºF´İÅú", (unsigned char *) "h06" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "²q", (unsigned char *) "h9 " },
	{ (unsigned char *) "±m±Ä¸Bºù½òªö", (unsigned char *) "h93" },
	{ (unsigned char *) "½²µæ", (unsigned char *) "h94" },
	{ (unsigned char *) "¤~°]§÷Å×µô", (unsigned char *) "h96" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "­Ü³É·É¿µ»a", (unsigned char *) "h; " },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¥^§w¼×Áo½µ", (unsigned char *) "hj/ " },
	{ (unsigned char *) "ÂO±q²F", (unsigned char *) "hj/6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ÆyÂ«¿y", (unsigned char *) "hj04" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "²Ê", (unsigned char *) "hj " },
	{ (unsigned char *) "«PÁL¼ØÂÙÃà¾LÃë", (unsigned char *) "hj4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "À¿", (unsigned char *) "h8 " },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "·b½RÁÎ", (unsigned char *) "hji " },
	{ (unsigned char *) "­í®À±¹¼¼¾V¿ù", (unsigned char *) "hji4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¶Ê±ZºR", (unsigned char *) "hjo " },
	{ (unsigned char *) "½A", (unsigned char *) "hjo3" },
	{ (unsigned char *) "²f·ñºé»A¯ÜµÑ", (unsigned char *) "hjo4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "§øµr", (unsigned char *) "hjp " },
	{ (unsigned char *) "¦¤", (unsigned char *) "hjp3" },
	{ (unsigned char *) "¦T¤o", (unsigned char *) "hjp4" },
	{ (unsigned char *) "¦s", (unsigned char *) "hjp6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¥Uµ¦°¼´Z´l´ú", (unsigned char *) "hk4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¯ó", (unsigned char *) "hl3" },
	{ (unsigned char *) "¹Ë±ä¼Ñº¨", (unsigned char *) "hl6" },
	{ (unsigned char *) "¾ŞÁW", (unsigned char *) "hl " },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "´ê¿ê", (unsigned char *) "h.4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "§Â¯K", (unsigned char *) "hp6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "³á®@", (unsigned char *) "ji " },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¯Î¶ä", (unsigned char *) "j/ " },
	{ (unsigned char *) "»c", (unsigned char *) "j/3" },
	{ (unsigned char *) "Â|", (unsigned char *) "j/4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "­æÅsÆW»d½Ü", (unsigned char *) "j0 " },
	{ (unsigned char *) "±ß°û©{®¾¸Jºí²ğ»µµp", (unsigned char *) "j03" },
	{ (unsigned char *) "¸U±{µÃ", (unsigned char *) "j04" },
	{ (unsigned char *) "¤Y§¹ª±¹xÒFĞK¦Å", (unsigned char *) "j06" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¶ã¦d«Î§Å¦Ã¦¾¯Q»zÂë", (unsigned char *) "j " },
	{ (unsigned char *) "¤­¥î«V¤È¼a¼­®¸ªZ»RÄM", (unsigned char *) "j3" },
	{ (unsigned char *) "°Èª«»~¤a¤Å¶õ¹í®©¥³±àÃú", (unsigned char *) "j4" },
	{ (unsigned char *) "§d§^­ø±ï¤ğµL¿¾¸¼ÄÓ", (unsigned char *) "j6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "«z´E«õºÚµì", (unsigned char *) "j8 " },
	{ (unsigned char *) "¥Ë", (unsigned char *) "j83" },
	{ (unsigned char *) "Äû", (unsigned char *) "j84" },
	{ (unsigned char *) "«½", (unsigned char *) "j86" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¬n", (unsigned char *) "j9 " },
	{ (unsigned char *) "¥~", (unsigned char *) "j94" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤q¨L", (unsigned char *) "j; " },
	{ (unsigned char *) "©¹±¦ªPºôªÉÃS", (unsigned char *) "j;3" },
	{ (unsigned char *) "¦k§Ñ©ô±æ", (unsigned char *) "j;4" },
	{ (unsigned char *) "¤ı¤`", (unsigned char *) "j;6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "­Ø´õºÛ¸±", (unsigned char *) "ji " },
	{ (unsigned char *) "§Ú", (unsigned char *) "ji3" },
	{ (unsigned char *) "´¤ºW¨U´ìª×ÆSØò", (unsigned char *) "ji4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "·Û¶j°¹«Â´Q", (unsigned char *) "jo " },
	{ (unsigned char *) "°¶©e®U§À¬¨µT·õ½nµä¸«½ÓÂC", (unsigned char *) "jo3" },
	{ (unsigned char *) "¦ì°°¨ı³Ş±L¼¢¥¼´ô¬È­G½«½Ã¿×ÁºÁıÃQ", (unsigned char *) "jo4" },
	{ (unsigned char *) "¬°¦M°ß³òÄŞ±c´W·L±©®éÀåºûÁ¨¹HÁò­³", (unsigned char *) "jo6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "·Å¶ó½E", (unsigned char *) "jp " },
	{ (unsigned char *) "¦F§kÃ­", (unsigned char *) "jp3" },
	{ (unsigned char *) "°İ§î¨Z¯¿", (unsigned char *) "jp4" },
	{ (unsigned char *) "¤åª³¯¾°A¶²»D", (unsigned char *) "jp6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "°ş", (unsigned char *) "k " },
	{ (unsigned char *) "«X¤Ì§c¾µ°î´c´j§ã¸°¸ã³m¹K¶kÁîÃE¾jÆs", (unsigned char *) "k4" },
	{ (unsigned char *) "®Z®o³H¸¿³_ÃBÃZ", (unsigned char *) "k6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¥W", (unsigned char *) "l " },
	{ (unsigned char *) "¶şÃÍ", (unsigned char *) "l3" },
	{ (unsigned char *) "¶Æ¶ø¾Ò¿D", (unsigned char *) "l4" },
	{ (unsigned char *) "¹È±Î¼õ¿¬Ám¾CÃïÆR", (unsigned char *) "l6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤ê¬ù", (unsigned char *) "m, " },
#ifdef  WIN32
	{ (unsigned char *) "¤ë¼Ö¾\¦G©¨À®®®ªµÅÔ¸f¶VÅD°c", (unsigned char *) "m,4" },
#else
	{ (unsigned char *) "¤ë¼Ö¾\\¦G©¨À®®®ªµÅÔ¸f¶VÅD°c", (unsigned char *) "m,4" },
#endif  /*WIN32*/
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¶Ä¾Ã±eºHÁs°o»Á¹l", (unsigned char *) "m/ " },
	{ (unsigned char *) "¥Ã«M«i±v¾Öªa¯F´é¨i¸ºµú¿ã", (unsigned char *) "m/3" },
	{ (unsigned char *) "¥Î¦ş", (unsigned char *) "m/4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "­Ş²W»ğÀp", (unsigned char *) "m0 " },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "Ä@»·«èº@­b°|", (unsigned char *) "m04" },
	{ (unsigned char *) "¤¸­ì­û¶é¶ê«®´D´©¨JµE·½¬¸·á½t°KÁÕÄÍ", (unsigned char *) "m06" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "²J·ï¬ú¨±", (unsigned char *) "m " },
	{ (unsigned char *) "¤©«B»y»P®F°ë¦tÀ¬±h±Ö¬ê¦ĞÅÅ", (unsigned char *) "m3" },
	{ (unsigned char *) "¥É¨|³ë°ì¹á´J±s·U¼¤¬R±ı·¶¯D·Ôº»ºÇÂ¡¿mÆ~¸Î¿ÙÅA¿İ­§¹w¶¿Æ{à±", (unsigned char *) "m4" },
#ifdef  WIN32
	{ (unsigned char *) "¤_§E«\³½¦f§±®T·M´r©ó·®Âj´üº®·ìª»¬ë¬òµÍªØµã¸·½Â½É¿Ì½ÛÁÖ¹O¾l", (unsigned char *) "m6" },
#else
	{ (unsigned char *) "¤_§E«\\³½¦f§±®T·M´r©ó·®Âj´üº®·ìª»¬ë¬òµÍªØµã¸·½Â½É¿Ì½ÛÁÖ¹O¾l", (unsigned char *) "m6" },
#endif  /*WIN32*/
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "·wºr", (unsigned char *) "mp " },
	{ (unsigned char *) "¤¹¹k", (unsigned char *) "mp3" },
	{ (unsigned char *) "¥¥¹B·Y¼÷Ä­ÁßÃı", (unsigned char *) "mp4" },
	{ (unsigned char *) "¤ª¤Ã©û¸a¯Æ¯Ğªå¶³", (unsigned char *) "mp6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¥q¼R¼r«ä¼¹´µ¨pµ·Åî", (unsigned char *) "n " },
	{ (unsigned char *) "¦º", (unsigned char *) "n3" },
	{ (unsigned char *) "¥|¦ü¦ø«S¨á¶à©q¦x¤xªrªÁ²à¸v½ç¹}¾o", (unsigned char *) "n4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "·j»`ÄBÃI", (unsigned char *) "n. " },
	{ (unsigned char *) "­î¹¾Â]ÃÁ", (unsigned char *) "n.3" },
	{ (unsigned char *) "¹Â", (unsigned char *) "n.4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤T", (unsigned char *) "n0 " },
	{ (unsigned char *) "³Ê´²ÁX", (unsigned char *) "n03" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "Åx¼»Ïs", (unsigned char *) "n83" },
	{ (unsigned char *) "¤ÊÂÄ»ã", (unsigned char *) "n84" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¸|ÄÎ", (unsigned char *) "n9 " },
	{ (unsigned char *) "ÁÉ", (unsigned char *) "n94" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "³à®á", (unsigned char *) "n; " },
	{ (unsigned char *) "¶Ú", (unsigned char *) "n;3" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ÅÈµd¿qÄ¬¶p", (unsigned char *) "nj " },
	{ (unsigned char *) "¶D³t¶ì¦g±J·¹ÁPµ¯¯ÀµÂ½¶¶è", (unsigned char *) "nj4" },
	{ (unsigned char *) "«U", (unsigned char *) "nj6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ªQ±]·C§Ø²SÃP", (unsigned char *) "nj/ " },
	{ (unsigned char *) "®ª¼£Áq", (unsigned char *) "nj/3" },
	{ (unsigned char *) "§º³^»w°e¹|", (unsigned char *) "nj/4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "µm»Ä", (unsigned char *) "nj0 " },
	{ (unsigned char *) "ºâ»[", (unsigned char *) "nj04" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "­ö¶Û®P±ô¿uÁY»b", (unsigned char *) "nji " },
	{ (unsigned char *) "©Òº¾¯ÁÂê", (unsigned char *) "nji3" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "Áö¸F¸k", (unsigned char *) "njo " },
	{ (unsigned char *) "Åè", (unsigned char *) "njo3" },
	{ (unsigned char *) "·³Àæ¸H¯©ÁJ½Ù¹EÂãÀG", (unsigned char *) "njo4" },
	{ (unsigned char *) "¶¦ÀH", (unsigned char *) "njo6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "®]»^¶¸¼ò", (unsigned char *) "njp " },
	{ (unsigned char *) "·lºgµ«", (unsigned char *) "njp3" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¶Ş§£¶ëÀß·æÂ¨¦â", (unsigned char *) "nk4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "Áb¿´ÄÌ·k", (unsigned char *) "nl " },
	{ (unsigned char *) "±½·A", (unsigned char *) "nl3" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "´Ë", (unsigned char *) "np " },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "®¦¶â", (unsigned char *) "p " },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "©á²i¯y", (unsigned char *) "q/ " },
	{ (unsigned char *) "±·", (unsigned char *) "q/3" },
	{ (unsigned char *) "¸I", (unsigned char *) "q/4" },
	{ (unsigned char *) "ªB´^´×¼ê¸NÁO¿±½´ÄP", (unsigned char *) "q/6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "Ãk¼ï", (unsigned char *) "q0 " },
	{ (unsigned char *) "§P«q©é¯`¬ß", (unsigned char *) "q04" },
	{ (unsigned char *) "ºn½L½Y­DÂÏ½í", (unsigned char *) "q06" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "°Ô¸´­w", (unsigned char *) "q8 " },
	{ (unsigned char *) "©È©¬", (unsigned char *) "q84" },
	{ (unsigned char *) "ªIª¦µ]¯Ò", (unsigned char *) "q86" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "©ç", (unsigned char *) "q9 " },
	{ (unsigned char *) "¬£´û", (unsigned char *) "q94" },
	{ (unsigned char *) "­Ö±r±ÆµP", (unsigned char *) "q96" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¥ã·¼", (unsigned char *) "q; " },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "·K®Ç¿ÀÃe", (unsigned char *) "q;6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "©Yªi¼â", (unsigned char *) "qi " },
	{ (unsigned char *) "¥r­å»á", (unsigned char *) "qi3" },
	{ (unsigned char *) "­¢¾z¬Ä¯}²ËÃæ", (unsigned char *) "qi4" },
	{ (unsigned char *) "±C¾I", (unsigned char *) "qi6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤²¼P¥·¼³", (unsigned char *) "qj " },
	{ (unsigned char *) "´¶®E®H®ú·Á»§ÃĞ", (unsigned char *) "qj3" },
	{ (unsigned char *) "ÃnÂr¾Q", (unsigned char *) "qj4" },
#ifdef  WIN32
	{ (unsigned char *) "¦µ¾ëÀä¿\²ãµĞ¸²»ZÃÚ°z«m", (unsigned char *) "qj6" },
#else
	{ (unsigned char *) "¦µ¾ëÀä¿\\²ãµĞ¸²»ZÃÚ°z«m", (unsigned char *) "qj6" },
#endif  /*WIN32*/
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "©ß", (unsigned char *) "ql " },
	{ (unsigned char *) "¶]", (unsigned char *) "ql3" },
	{ (unsigned char *) "ªw¬¶¯p¯¥", (unsigned char *) "ql4" },
	{ (unsigned char *) "°Ì©H©´³T", (unsigned char *) "ql6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "­F©A", (unsigned char *) "qo " },
#ifdef  WIN32
	{ (unsigned char *) "¨Ø¨K¯\Å¯°t", (unsigned char *) "qo4" },
#else
	{ (unsigned char *) "¨Ø¨K¯\\Å¯°t", (unsigned char *) "qo4" },
#endif  /*WIN32*/
	{ (unsigned char *) "°ö»p½ß³­", (unsigned char *) "qo6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¼Q", (unsigned char *) "qp " },
	{ (unsigned char *) "¬Ö", (unsigned char *) "qp6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¥A¼A¤Ç§¥§å©ÜÅR", (unsigned char *) "qu " },
	{ (unsigned char *) "¥ö¥Ôµl", (unsigned char *) "qu3" },
	{ (unsigned char *) "»÷·B§¾Â}Ä´ÅP", (unsigned char *) "qu4" },
#ifdef  WIN32
	{ (unsigned char *) "°à°ñªJ¬sµ\¯h¥Ö¯ÄµÊ¹e«@³²Åg", (unsigned char *) "qu6" },
#else
	{ (unsigned char *) "°à°ñªJ¬sµ\\¯h¥Ö¯ÄµÊ¹e«@³²Åg", (unsigned char *) "qu6" },
#endif  /*WIN32*/
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ºJ¿h", (unsigned char *) "qu, " },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
#ifdef  WIN32
	{ (unsigned char *) "®\¥â", (unsigned char *) "qu/ " },
#else
	{ (unsigned char *) "®\\¥â", (unsigned char *) "qu/ " },
#endif  /*WIN32*/
	{ (unsigned char *) "¥­©W«Ì¾Ì¬i²~µÓÄ«µû", (unsigned char *) "qu/6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "°¾½g½¡", (unsigned char *) "qu0 " },
	{ (unsigned char *) "¤ùÄF", (unsigned char *) "qu04" },
	{ (unsigned char *) "¯â½ÊÀc", (unsigned char *) "qu06" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ÄÆº}", (unsigned char *) "qul " },
	{ (unsigned char *) "¿gÁe", (unsigned char *) "qul3" },
	{ (unsigned char *) "²¼¶ÑÅY", (unsigned char *) "qul4" },
	{ (unsigned char *) "¹â¿]", (unsigned char *) "qul6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "«¹«÷", (unsigned char *) "qup " },
	{ (unsigned char *) "«~", (unsigned char *) "qup3" },
	{ (unsigned char *) "¸u¦É", (unsigned char *) "qup4" },
	{ (unsigned char *) "³hÀ§ÀWÆI", (unsigned char *) "qup6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "©~©ëª®¯j¾s", (unsigned char *) "rm " },
	{ (unsigned char *) "Á|©Cªq¯x²÷ÄÔ", (unsigned char *) "rm3" },
	{ (unsigned char *) "¥¨­Ñ¥yÀ«Äß©Ú¾Ú¬²»E­U¶Z½õÁØ¹d¿÷Áü¨ã­Ğ¼@", (unsigned char *) "rm4" },
	{ (unsigned char *) "§½«]±Å®Ü¾ïµâ»±Áù", (unsigned char *) "rm6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¨Mµ´Ä±¹»­Ï³ÖÄZ¤n±U¿¹Å©³ZÃÔÃİ¾¡§à±¸ÅÌÀï", (unsigned char *) "rm,6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¬³µ~­~", (unsigned char *) "rm/3" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "®S®½®şÅOÃY", (unsigned char *) "rm0 " },
	{ (unsigned char *) "±²", (unsigned char *) "rm03" },
	{ (unsigned char *) "¨÷­Â°é¯X²²¸h¹m", (unsigned char *) "rm04" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "§g§¡­x¶v", (unsigned char *) "rmp " },
	{ (unsigned char *) "«T®m¯CÀàµ¤µß°pÂ@", (unsigned char *) "rmp4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤L¥ä¿n¼T°ò®V®j´R¾÷¿E¶ÖµQ¿Y½B·îÁF½]ºßÁZÅù¦ÙÃÕ¸ñÂİÂûÅE°§ÄÈ", (unsigned char *) "ru " },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¶Ø±µ´¦¬Òµó¶¥", (unsigned char *) "ru, " },
	{ (unsigned char *) "©n©j¸Ñ", (unsigned char *) "ru,3" },
	{ (unsigned char *) "¤¶­É©¡§Ù¬É¬ÎªãÂÇ»|", (unsigned char *) "ru,4" },
	{ (unsigned char *) "³Ç§T¤mºI±¶Â^ªN®åÀÍ¼ä·ûºÔºÜ¸`µ²½~°P¸×¾e", (unsigned char *) "ru,6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "³î´ªªÈ¹§", (unsigned char *) "ru. " },
	{ (unsigned char *) "¤[¤E¨b¨h­v°s­´", (unsigned char *) "ru.3" },
#ifdef  WIN32
	{ (unsigned char *) "±Ï©S´N´\¬^ª¹¨s¦İ¸¤ÂÂ", (unsigned char *) "ru.4" },
#else
	{ (unsigned char *) "±Ï©S´N´\\¬^ª¹¨s¦İ¸¤ÂÂ", (unsigned char *) "ru.4" },
#endif  /*WIN32*/
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¨Ê¹¸±Ü´¹®ù·úºë¯ğ²ôµ×ÅåÄH¸g", (unsigned char *) "ru/ " },
	{ (unsigned char *) "¤«¼©´º¿[Äµ¨ÀÀV", (unsigned char *) "ru/3" },
	{ (unsigned char *) "«l¹Ò®|·q²bµj³º³wÃè¹tÀRÄv", (unsigned char *) "ru/4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "­İ°í¦l«Á¦yªÓ¶¡Äè´æ·ÎºÊºà½p¿¡Á}µÕÆi", (unsigned char *) "ru0 " },
	{ (unsigned char *) "»ü°Å´z¾ß¬ZÀË´îÂ¥¸cÂ²ÃµÆP", (unsigned char *) "ru03" },
	{ (unsigned char *) "¨£¥ó°·¹°¼C«Ø··º¥¼îÂq½b¸xÄ¥¯òÂË¿Ï½â½îÁäÅ²Å³À^", (unsigned char *) "ru04" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤v´X´uÀ½µ¹¹¨", (unsigned char *) "ru3" },
	{ (unsigned char *) "©u¾¯¬ö­p°O»ÚÅ´§Ò±ª§Ş¬Jº[¬­ÀÙ²½½^¾¬Ä~ªçÁªÂÉÁ»ÆkÀgÃV§²±H", (unsigned char *) "ru4" },
	{ (unsigned char *) "¦N¿è¶°«E¥ù§Y¤Î®A¶ú±I§Ä«æ·aÀ»´Æ·ª·¥¯e½CÄy¯Å¯á¨V", (unsigned char *) "ru6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¨Î³Ã¥[¹Å®a¯m³P¿Ş­{", (unsigned char *) "ru8 " },
	{ (unsigned char *) "°²¥Ò¸ë¹[", (unsigned char *) "ru83" },
	{ (unsigned char *) "»ù¶ù¬[½[¾r", (unsigned char *) "ru84" },
	{ (unsigned char *) "§¨±®®µ¯H²óÀU", (unsigned char *) "ru86" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¦¿¼ßÃ¦Á¤Å·±N»ø«¸", (unsigned char *) "ru; " },
	{ (unsigned char *) "Á¿¼ú¼Õ½±", (unsigned char *) "ru;3" },
	{ (unsigned char *) "¦Kµ¼Âæ­°", (unsigned char *) "ru;4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¥æ¼b´Ô¼åÁG½¦¿¼µë¸å¸ø­¥ÅºÂBµJ", (unsigned char *) "rul " },
	{ (unsigned char *) "¨¤Ãº¸}¹®¶Ï¶Ó«»ÅÍ¬¾²®ÁBµ±»Ç»å", (unsigned char *) "rul3" },
	{ (unsigned char *) "¥s±Ğµ¢¸ûÃâÃç", (unsigned char *) "rul4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤µ¤y¤ç¬áµ¬ÃÌ­oª÷¬z", (unsigned char *) "rup " },
	{ (unsigned char *) "¶È¾¨½@ºòÂÔÀAÄD", (unsigned char *) "rup3" },
	{ (unsigned char *) "¶iªñ¾¶®Ê®ûÂuºÉ¸T¿§ÂÑ", (unsigned char *) "rup4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¯à", (unsigned char *) "s/6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¦_³i", (unsigned char *) "s03" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "³ä·£¨kÃø«n", (unsigned char *) "s06" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "®R¨º­ş§o±Ì¯Ç³[¶u", (unsigned char *) "s84" },
	{ (unsigned char *) "®³", (unsigned char *) "s86" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤D¥¤¦»°i", (unsigned char *) "s93" },
	{ (unsigned char *) "­@©`", (unsigned char *) "s94" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "Ää", (unsigned char *) "s;3" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "Ån", (unsigned char *) "s;6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "§Ë", (unsigned char *) "sj/4" },
	{ (unsigned char *) "¹A»ú¾º¿@ÂªÁw", (unsigned char *) "sj/6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "·x", (unsigned char *) "sj03" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "§V©¸¥£¾q", (unsigned char *) "sj3" },
	{ (unsigned char *) "«ã", (unsigned char *) "sj4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "À¶Äz¿Õ", (unsigned char *) "sji4" },
	{ (unsigned char *) "®¿", (unsigned char *) "sji6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "´o·ê¸£", (unsigned char *) "sl3" },
	{ (unsigned char *) "¾x", (unsigned char *) "sl4" },
	{ (unsigned char *) "©L¼¸¾øÄÂ", (unsigned char *) "sl6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ºÄ­h", (unsigned char *) "sm,4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤k", (unsigned char *) "sm3" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¾k", (unsigned char *) "so3" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤º", (unsigned char *) "so4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "®º", (unsigned char *) "su, " },
#ifdef  WIN32
	{ (unsigned char *) "Ä^ÄÙ¯IÂ¿¯åÄôÆ\ÂìÆhÅj", (unsigned char *) "su,4" },
#else
	{ (unsigned char *) "Ä^ÄÙ¯IÂ¿¯åÄôÆ\\ÂìÆhÅj", (unsigned char *) "su,4" },
#endif  /*WIN32*/
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "§¬", (unsigned char *) "su. " },
	{ (unsigned char *) "§×§á¯Ã¶s", (unsigned char *) "su.3" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤û", (unsigned char *) "su.6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¦ğÀ×", (unsigned char *) "su/4" },
	{ (unsigned char *) "À¾¾®À{¹çÂfÀñ", (unsigned char *) "su/6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "©à±É¼¿Â[¯G½V½û", (unsigned char *) "su03" },
	{ (unsigned char *) "°á¤Ü©À", (unsigned char *) "su04" },
	{ (unsigned char *) "¦~ÂH", (unsigned char *) "su06" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "§A©pÀÀ±İ", (unsigned char *) "su3" },
	{ (unsigned char *) "°Î¼Ê·Ä¸E¿°°f", (unsigned char *) "su4" },
	{ (unsigned char *) "©O­Ù©g¥§©ËªdÀO", (unsigned char *) "su6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ÆC", (unsigned char *) "su;4" },
	{ (unsigned char *) "®QÄ]", (unsigned char *) "su;6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¾Å¸Í³¾", (unsigned char *) "sul3" },
	{ (unsigned char *) "§¿", (unsigned char *) "sul4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "±z", (unsigned char *) "sup6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¦Y³ğ¶á·öÃ¨²Ç°EÅ^", (unsigned char *) "t " },
	{ (unsigned char *) "®¢¨×§`¤Ø¿É³a¾¦", (unsigned char *) "t3" },
	{ (unsigned char *) "³×±Õ¥¸¿K¯Í¨ª¶½¥w", (unsigned char *) "t4" },
	{ (unsigned char *) "«ù°Í¼U¦¢¦À½ó¿ğ¹£", (unsigned char *) "t6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "©â", (unsigned char *) "t. " },
	{ (unsigned char *) "¤¡Áà", (unsigned char *) "t.3" },
	{ (unsigned char *) "¯ä", (unsigned char *) "t.4" },
	{ (unsigned char *) "¤³¾©±¨·TÃ¥¸YÄwº÷»vÅC¹SÃW", (unsigned char *) "t.6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ºÙ¼µ¿e", (unsigned char *) "t/ " },
	{ (unsigned char *) "³xÁş", (unsigned char *) "t/3" },
	{ (unsigned char *) "¯¯", (unsigned char *) "t/4" },
	{ (unsigned char *) "¦¨µ{¥à­¼§e«°Ãg©Ó¾í¼á¸Û", (unsigned char *) "t/6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "Äe", (unsigned char *) "t0 " },
	{ (unsigned char *) "²£¶Ğ½ÔÃêÄÄ", (unsigned char *) "t03" },
	{ (unsigned char *) "Ã_ÄbÄó¼`´GÄ`ÁIÄñÂÍÃÊÅşÆa", (unsigned char *) "t06" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤e®t´¡", (unsigned char *) "t8 " },
	{ (unsigned char *) "«b§Ã¸Ò", (unsigned char *) "t84" },
	{ (unsigned char *) "¹î·g¬d¯ù", (unsigned char *) "t86" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "©î³¦", (unsigned char *) "t9 " },
	{ (unsigned char *) "¾«®ã°[", (unsigned char *) "t96" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "­Î±@©÷²sÄI", (unsigned char *) "t; " },
	{ (unsigned char *) "¼t´¯¾û", (unsigned char *) "t;3" },
	{ (unsigned char *) "­Ò°Û±£ºZ", (unsigned char *) "t;4" },
	{ (unsigned char *) "±`ªøÀv¹ÁÀ|³õ¹ß±u¸zµç", (unsigned char *) "t;6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¥R¼¥¨R²ê½Ä", (unsigned char *) "th/ " },
	{ (unsigned char *) "Ãd", (unsigned char *) "tj/3" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "±RÂÎ", (unsigned char *) "tj/6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤t¬ï", (unsigned char *) "tj0 " },
	{ (unsigned char *) "³İ¦ß", (unsigned char *) "tj03" },
	{ (unsigned char *) "¦ê³©", (unsigned char *) "tj04" },
	{ (unsigned char *) "¶Ç²î", (unsigned char *) "tj06" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¥XªìÄÕ", (unsigned char *) "tj " },
	{ (unsigned char *) "ªS·¡´ØÂ¦»u", (unsigned char *) "tj3" },
	{ (unsigned char *) "¯b©ÅÀÓÅ÷²Ò³BÄ²ÂJ", (unsigned char *) "tj4" },
	{ (unsigned char *) "°£Àx¼pÃo¯ìÃÜ¾SÂú", (unsigned char *) "tj6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "´¢", (unsigned char *) "tj93" },
	{ (unsigned char *) "¿å", (unsigned char *) "tj94" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "µ¡½H", (unsigned char *) "tj; " },
	{ (unsigned char *) "Âô", (unsigned char *) "tj;3" },
	{ (unsigned char *) "³Ğ·[", (unsigned char *) "tj;4" },
	{ (unsigned char *) "§É¼l", (unsigned char *) "tj;6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ÂW", (unsigned char *) "tji " },
	{ (unsigned char *) "°ãºï½ùÅÆ", (unsigned char *) "tji4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "§jª¤", (unsigned char *) "tjo " },
	{ (unsigned char *) "««´¨ºl½iÁèÂñ¶«", (unsigned char *) "tjo6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¬K", (unsigned char *) "tjp " },
	{ (unsigned char *) "Äø", (unsigned char *) "tjp3" },
	{ (unsigned char *) "®B²E¯Â²å¾JÄL", (unsigned char *) "tjp6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¨®", (unsigned char *) "tk " },
	{ (unsigned char *) "§è", (unsigned char *) "tk3" },
#ifdef  WIN32
	{ (unsigned char *) "©\¹ı´wºMº«Âá", (unsigned char *) "tk4" },
#else
	{ (unsigned char *) "©\\¹ı´wºMº«Âá", (unsigned char *) "tk4" },
#endif  /*WIN32*/
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¶r§Û¶W", (unsigned char *) "tl " },
	{ (unsigned char *) "§nª£", (unsigned char *) "tl3" },
	{ (unsigned char *) "¼J±_®Ğ¼é", (unsigned char *) "tl6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "µ`½Q", (unsigned char *) "tp " },
	{ (unsigned char *) "Äh¬ÏÅ¨Æ@¶X", (unsigned char *) "tp4" },
	{ (unsigned char *) "³¯¹Ğ®f§Õ±á¨I¦Ú¿Û¨°", (unsigned char *) "tp6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¼O", (unsigned char *) "u, " },
	{ (unsigned char *) "¤]§M³¥", (unsigned char *) "u,3" },
	{ (unsigned char *) "©]¾ç·~¸­¿Ö¿óÅâ­¶", (unsigned char *) "u,4" },
	{ (unsigned char *) "·¦·İ²x­C", (unsigned char *) "u,6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "Àu¼~«Õ±y§ñ", (unsigned char *) "u. " },
	{ (unsigned char *) "¤Í¦³¼ø²û¨»ÂK", (unsigned char *) "u.3" },
	{ (unsigned char *) "¥k¦ö¨İ¤S«ª«É¥®¬c¯§»¤¹VÃ^", (unsigned char *) "u.4" },
#ifdef  WIN32
	{ (unsigned char *) "¤×ªo´åµS·ß¥Ñ¬Ğ¹C¶l¹\¾{", (unsigned char *) "u.6" },
#else
	{ (unsigned char *) "¤×ªo´åµS·ß¥Ñ¬Ğ¹C¶l¹\\¾{", (unsigned char *) "u.6" },
#endif  /*WIN32*/
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "­^ÄXÀ¦À³Äå·ëÄíÅÕÄ¢ÅaÆNÆx", (unsigned char *) "u/ " },
	{ (unsigned char *) "¼v¿o°r", (unsigned char *) "u/3" },
	{ (unsigned char *) "¬Mµw", (unsigned char *) "u/4" },
	{ (unsigned char *) "ªïÄ¹¶÷º·Àç¼ü¬Õ¿¢¿ÃÃÇ", (unsigned char *) "u/6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "«|©a¹ä²T´ó²j·Ï¯ÚµËµÒ¾M", (unsigned char *) "u0 " },
	{ (unsigned char *) "ºt²´°³Åk«^±»­l¶nÆLÅÄ", (unsigned char *) "u03" },
	{ (unsigned char *) "¹½ÆA­ñÃ`³÷®b«Û®ËµK¿V¿Pµx¿ÎÆvÅ¬Æo¶­ÅäÅç", (unsigned char *) "u04" },
	{ (unsigned char *) "ÄY§°©¥ÅÉ©µÀÑªuª¢Àù¬ãºáÃ²¨¥ÀFÃCÆQ", (unsigned char *) "u06" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤@¥ì¨Ì«©¾³³ü´¥º¬¦çÂå", (unsigned char *) "u " },
	{ (unsigned char *) "¤A¥H­Ê°À¤wºY´È¨oÃÆ¨²­£", (unsigned char *) "u3" },
	{ (unsigned char *) "¥ç§H¨Û»õÅm«³¦z«Ù¤|§Ğ·N¾ĞÅt§í±³©ö¦²¼İ²G·¸²§¬Ì¯q¿~Ã¶¸q¬ı²İÁk¸wµÅÃÀ»i¸Ç¸ÚÄ³Ä¶¶c¶h¨¶ÂïÅæÁlÁr", (unsigned char *) "u4" },
	{ (unsigned char *) "¿ò»ö«x¦e¦i«¼©yÂU©É®ë¨^ºÃ²­²¾¯Ø½Ë¶MÀ[¹~", (unsigned char *) "u6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "§rÀ£©ãÀn¾~¤X", (unsigned char *) "u8 " },
	{ (unsigned char *) "¶®°×", (unsigned char *) "u83" },
	{ (unsigned char *) "¨È´ã³Y", (unsigned char *) "u84" },
	{ (unsigned char *) "²P¤úªŞ°H¸Å", (unsigned char *) "u86" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¥¡¬oªt¯±»ßÀm", (unsigned char *) "u; " },
	{ (unsigned char *) "¥õ®ñÄo¾i", (unsigned char *) "u;3" },
	{ (unsigned char *) "©Â®~¼Ëºy", (unsigned char *) "u;4" },
	{ (unsigned char *) "¨Ë«â´­·z·¨¬v·ÕºÅ¦ÏÁí¶§ÃG", (unsigned char *) "u;6" },
	{ (unsigned char *) "", (unsigned char *) "" },
#ifdef  WIN32
	{ (unsigned char *) "­ò¤\¦[³é¤Ô§¯¸yÁÜ", (unsigned char *) "ul " },
#else
	{ (unsigned char *) "­ò¤\\¦[³é¤Ô§¯¸yÁÜ", (unsigned char *) "ul " },
#endif  /*WIN32*/
	{ (unsigned char *) "«r¯·¯æ", (unsigned char *) "ul3" },
	{ (unsigned char *) "­nÃÄÄ£©íÂ`Æ_Åc", (unsigned char *) "ul4" },
#ifdef  WIN32
	{ (unsigned char *) "³ó«À±\·nºo¬«²c¤øº½½`ªÔ»»ÁÁ", (unsigned char *) "ul6" },
#else
	{ (unsigned char *) "³ó«À±\\·nºo¬«²c¤øº½½`ªÔ»»ÁÁ", (unsigned char *) "ul6" },
#endif  /*WIN32*/
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¦]«Ã¹ş®ï®ô¯ô³±­µ", (unsigned char *) "up " },
	{ (unsigned char *) "§v¤¨¤ŞÅ}°CÁô¶¼Ái", (unsigned char *) "up3" },
	{ (unsigned char *) "¦L­N½®", (unsigned char *) "up4" },
	{ (unsigned char *) "«­¹Û±G²]»Â»ÈÃùÅi§u", (unsigned char *) "up6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¾»Á§¹u", (unsigned char *) "vm, " },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "«d¥Ş³·", (unsigned char *) "vm,4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¥S¥û¤¿¦I¬¤¯İ", (unsigned char *) "vm/ " },
	{ (unsigned char *) "¶¯ºµ", (unsigned char *) "vm/6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "«Å³Ù®Ï·y·Ü¸©¿Ü°a", (unsigned char *) "vm0 " },
	{ (unsigned char *) "¿ï", (unsigned char *) "vm03" },
	{ (unsigned char *) "±Û¬¯´è¯tµº¹b", (unsigned char *) "vm04" },
	{ (unsigned char *) "Äaºx¥ÈÂ{", (unsigned char *) "vm06" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¶·»İ¦S¼N¼V¦¦­Eµê°XÅ½", (unsigned char *) "vm " },
#ifdef  WIN32
	{ (unsigned char *) "³\®İ·Ö", (unsigned char *) "vm3" },
#else
	{ (unsigned char *) "³\\®İ·Ö", (unsigned char *) "vm3" },
#endif  /*WIN32*/
	{ (unsigned char *) "§Ç±å¨ù´B«ò±Ô¦°¬®µ¶ºüÄò»W³¤¹z", (unsigned char *) "vm4" },
	{ (unsigned char *) "®}", (unsigned char *) "vm6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "³Ô¾±À¥ÂtÂÈÅH", (unsigned char *) "vmp " },
	{ (unsigned char *) "¨³®î´S¦Ä¿¸°T°V»¹¹¥", (unsigned char *) "vmp4" },
	{ (unsigned char *) "¨µ«à´`¦¯¬¬¼ñ¯û¸ß´M", (unsigned char *) "vmp6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¹¯¤¼§l®D¼H®O¼^§Æ±xÄâªR²X·Ë²mº³µRÄëÁH¿Qµ}¿ª½¥¦è»hÁµÃÖÁÆÁÑ", (unsigned char *) "vu " },
	{ (unsigned char *) "³ß±p¬~Ã¢", (unsigned char *) "vu3" },
	{ (unsigned char *) "¨t«Y¤iÀ¸¦Á¼óª¿²ÓÃ´µ¿»Ø", (unsigned char *) "vu4" },
	{ (unsigned char *) "®u®§±¤©õÀÊº¶²ß»VÅ§¿ü·@", (unsigned char *) "vu6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¨Ç·²ÃÈ", (unsigned char *) "vu, " },
	{ (unsigned char *) "¼g¦å", (unsigned char *) "vu,3" },
	{ (unsigned char *) "¨ø®h¾Ó±ñ·¤ºkªn¬ªÂmÀè²ØÃÉÁ¶ÁÂÁÛ", (unsigned char *) "vu,4" },
	{ (unsigned char *) "°º¼E¨ó±×¯Ù¿Ó¨¸¾c", (unsigned char *) "vu,6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¥ğ­×«¦²Û²ç", (unsigned char *) "vu. " },
	{ (unsigned char *) "¦´", (unsigned char *) "vu.3" },
	{ (unsigned char *) "¶å©¦·Í¨qÂ¸³SÄÃ", (unsigned char *) "vu.4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¿³¬P´iµV¸{", (unsigned char *) "vu/ " },
	{ (unsigned char *) "¬Ù¿ô", (unsigned char *) "vu/3" },
	{ (unsigned char *) "©Ê©m­Æ©¯±¢§ö", (unsigned char *) "vu/4" },
	{ (unsigned char *) "¦æ¦D«¬§Î²º¨·°¤", (unsigned char *) "vu/6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¥P¥ı±È¾æ¬æªÄÅÖÂA", (unsigned char *) "vu0 " },
	{ (unsigned char *) "Å~Äö¸Ã»ÑÀIÅã", (unsigned char *) "vu03" },
	{ (unsigned char *) "²{¹·®s¾ËÄm½u¿¤¸r¸¢³A­­³´ÄÅÀ`", (unsigned char *) "vu04" },
	{ (unsigned char *) "«w°å¶û©¶²C²Í²ì½å»Î¶~¶¢ÄĞ¼_", (unsigned char *) "vu06" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "½¼½M", (unsigned char *) "vu8 " },
	{ (unsigned char *) "¤UÀ~®L·H", (unsigned char *) "vu84" },
#ifdef  WIN32
	{ (unsigned char *) "«L§X©E®l·v¬jª­¯U·åÁÒ¹IÃ\Áø", (unsigned char *) "vu86" },
#else
	{ (unsigned char *) "«L§X©E®l·v¬jª­¯U·åÁÒ¹IÃ\\Áø", (unsigned char *) "vu86" },
#endif  /*WIN32*/
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "­»´[´ğ¬Û½cÁ¸¶mÆ^Äì", (unsigned char *) "vu; " },
	{ (unsigned char *) "¨É·QÅT»èÅW", (unsigned char *) "vu;3" },
	{ (unsigned char *) "¹³¦VÂQ«Ñ¾ó¶µ¶H", (unsigned char *) "vu;4" },
	{ (unsigned char *) "«Ö²»µ¾¸Ô", (unsigned char *) "vu;6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "­ı¹ÌÄÛ®d±ú®øÃtµvÂ­¿½³p¾P¾]Å»", (unsigned char *) "vul " },
	{ (unsigned char *) "¤p¾åÁQ", (unsigned char *) "vul3" },
	{ (unsigned char *) "¯º§µ®Ä³Ë¼S®Õ¨v»Ã", (unsigned char *) "vul4" },
	{ (unsigned char *) "¾Ç", (unsigned char *) "vul6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤ß·s©ıªYªä²ñÁ~³`¨¯¾NÄÉ", (unsigned char *) "vup " },
	{ (unsigned char *) "«HÆ]", (unsigned char *) "vup4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "°½", (unsigned char *) "w. " },
	{ (unsigned char *) "³z", (unsigned char *) "w.4" },
	{ (unsigned char *) "§ëÀY", (unsigned char *) "w.6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¼ğ¯kÄğÃÃÁÃÄË", (unsigned char *) "w/6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "³g§~ÅuÅyÅõ", (unsigned char *) "w0 " },
	{ (unsigned char *) "©Z´à³R", (unsigned char *) "w03" },
	{ (unsigned char *) "¹Ä±´¼Û¬´ºÒ", (unsigned char *) "w04" },
	{ (unsigned char *) "¾Â¼u¾èÀÈ¼æ·ğÂ»µ÷½ÍÃÓ", (unsigned char *) "w06" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¥L¶ò¦o¥¦¨e", (unsigned char *) "w8 " },
	{ (unsigned char *) "¶ğ", (unsigned char *) "w83" },
	{ (unsigned char *) "½ñ¾ØºfºªÃ¡ÁÏÄ¾»¾»½", (unsigned char *) "w84" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "­L", (unsigned char *) "w9 " },
	{ (unsigned char *) "¤ÓºA¨O®õ", (unsigned char *) "w94" },
	{ (unsigned char *) "©ïÂi»O­aÂÊ¶`»ä¥x", (unsigned char *) "w96" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "´ö", (unsigned char *) "w; " },
	{ (unsigned char *) "­ÕÅl©®²I½ö", (unsigned char *) "w;3" },
	{ (unsigned char *) "¿S½ë", (unsigned char *) "w;4" },
	{ (unsigned char *) "­ğ°ó¶í·e´ÅºÁ¿}½£Á®ÁŞÃí", (unsigned char *) "w;6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¯S", (unsigned char *) "wk4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "³q", (unsigned char *) "wj/ " },
	{ (unsigned char *) "±íµ©²Î", (unsigned char *) "wj/3" },
	{ (unsigned char *) "ºEµh", (unsigned char *) "wj/4" },
	{ (unsigned char *) "¦Pµ£¹­«Ğ§Í®ä¼àÀû»É", (unsigned char *) "wj/6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "´ø", (unsigned char *) "wj0 " },
	{ (unsigned char *) "¹ÎÄ{", (unsigned char *) "wj06" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¨r", (unsigned char *) "wj " },
	{ (unsigned char *) "¦R¤g", (unsigned char *) "wj3" },
	{ (unsigned char *) "¨ßµé", (unsigned char *) "wj4" },
	{ (unsigned char *) "¥Y¹Ï®{¬ğ²ş³~»Æ±O¶î", (unsigned char *) "wj6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¦«©ì²æ°U", (unsigned char *) "wji " },
	{ (unsigned char *) "§´¾ò", (unsigned char *) "wji3" },
	{ (unsigned char *) "³è©İ¬l", (unsigned char *) "wji4" },
	{ (unsigned char *) "¦ïªb¶Yªû¹¤¾mÀk", (unsigned char *) "wji6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "±À", (unsigned char *) "wjo " },
	{ (unsigned char *) "»L", (unsigned char *) "wjo3" },
	{ (unsigned char *) "°h¸À", (unsigned char *) "wjo4" },
	{ (unsigned char *) "ÀZ", (unsigned char *) "wjo6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "§]", (unsigned char *) "wjp " },
	{ (unsigned char *) "¿Æ", (unsigned char *) "wjp4" },
	{ (unsigned char *) "§y¤ÙÁv³b¶»", (unsigned char *) "wjp6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¸l±Ç·ÊÃüÅ¹ÀÜ", (unsigned char *) "wl " },
	{ (unsigned char *) "°Q", (unsigned char *) "wl3" },
	{ (unsigned char *) "®M", (unsigned char *) "wl4" },
	{ (unsigned char *) "°k®ç°ŞÂh²^Âvµå³³", (unsigned char *) "wl6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¶K", (unsigned char *) "wu, " },
	{ (unsigned char *) "©«ÅK", (unsigned char *) "wu,3" },
	{ (unsigned char *) "ÃK", (unsigned char *) "wu,4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "Å¥ÆU¥Å", (unsigned char *) "wu/ " },
	{ (unsigned char *) "®¼±ò¸¥", (unsigned char *) "wu/3" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "«F°±´@®x§Ê", (unsigned char *) "wu/6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤Ñ²K", (unsigned char *) "wu0 " },
	{ (unsigned char *) "©½µÉ»QÀS", (unsigned char *) "wu03" },
	{ (unsigned char *) "¶ñ«ï²¢¥Ğ¬ËÂõ", (unsigned char *) "wu06" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "­ç±è½ğ", (unsigned char *) "wu " },
	{ (unsigned char *) "Åé", (unsigned char *) "wu3" },
	{ (unsigned char *) "«cÀ¡±P®­±§´À®÷³|¾O", (unsigned char *) "wu4" },
	{ (unsigned char *) "ÃD³Ú³ö´£¿á¶¬½{", (unsigned char *) "wu6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¬D²À", (unsigned char *) "wul " },
	{ (unsigned char *) "²·¸Ğ¸õ", (unsigned char *) "wul4" },
	{ (unsigned char *) "½Õ¨Ù±ø»m­|", (unsigned char *) "wul6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ºOÁM", (unsigned char *) "x.3" },
	{ (unsigned char *) "º|¿bÃó­®", (unsigned char *) "x.4" },
#ifdef  WIN32
	{ (unsigned char *) "¹Æ°úÁ²Å\¼Ó", (unsigned char *) "x.6" },
#else
	{ (unsigned char *) "¹Æ°úÁ²Å\\¼Ó", (unsigned char *) "x.6" },
#endif  /*WIN32*/
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "§N", (unsigned char *) "x/3" },
	{ (unsigned char *) "´h·«", (unsigned char *) "x/4" },
	{ (unsigned char *) "¸WÔ÷", (unsigned char *) "xu/6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ÃiÅóÆVÆlÄı", (unsigned char *) "x03" },
	{ (unsigned char *) "ÀİÄê", (unsigned char *) "x04" },
	{ (unsigned char *) "Äõ°ı´PÄdÄãÄæÄiÄxÂÅÄ°", (unsigned char *) "x06" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "©Ô", (unsigned char *) "x8 " },
	{ (unsigned char *) "³â", (unsigned char *) "x83" },
	{ (unsigned char *) "«fÃ¾Äú»¶", (unsigned char *) "x84" },
	{ (unsigned char *) "Ãå", (unsigned char *) "x86" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¿àÃuÄî·ıÅ£", (unsigned char *) "x94" },
	{ (unsigned char *) "¨Ó±tµÜ", (unsigned char *) "x96" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "®Ô", (unsigned char *) "x;3" },
	{ (unsigned char *) "®ö", (unsigned char *) "x;4" },
	{ (unsigned char *) "´Y·}¯T²w·ã½¸­¦", (unsigned char *) "x;6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "Ãb", (unsigned char *) "xj/3" },
	{ (unsigned char *) "¶©ÀsÄVÄgÄnÄïÁKÅ¢Å¤", (unsigned char *) "xj/6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¶Ã", (unsigned char *) "xj04" },
	{ (unsigned char *) "ÅrÆeÆqÆ}", (unsigned char *) "xj06" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ÂP", (unsigned char *) "xj " },
	{ (unsigned char *) "¾|¾ÛÃrº±¸¸³¿", (unsigned char *) "xj3" },
	{ (unsigned char *) "¸ô¿ı³°³À¶Î¼®´â¸L¸S¿r¸ïÅSÆOÄS", (unsigned char *) "xj4" },
	{ (unsigned char *) "ÃfÃyÄl¿cÄ¤ÄªÆDÆ`Æt", (unsigned char *) "xj6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "»r", (unsigned char *) "xji3" },
	{ (unsigned char *) "«£Àd¬¥¯Oºº¯_µ¸¸¨¹T»Ü", (unsigned char *) "xji4" },
	{ (unsigned char *) "Ã¹ÄØÅoÅzÅÚÁ³ÅŞÃñÆrÅ[ÆY", (unsigned char *) "xji6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ÃlÃ÷", (unsigned char *) "xj/3" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¨Ú­Û±[±Á²_ºú½×½ü", (unsigned char *) "xjp6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "°Ç©U¦Ø", (unsigned char *) "xk4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¼´", (unsigned char *) "xl " },
	{ (unsigned char *) "¦Ñ¨Ğ«¾", (unsigned char *) "xl3" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "³Ò¼G¨cÀ÷", (unsigned char *) "xl6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "±°²¤", (unsigned char *) "xm,4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ÅpÅË", (unsigned char *) "xj06" },
	{ (unsigned char *) "§Z", (unsigned char *) "xj03" },
	{ (unsigned char *) "", (unsigned char *) "" },
#ifdef  WIN32
	{ (unsigned char *) "«Q§f¹ğ¼i®ÈÁ\»MÁ¹¾T", (unsigned char *) "xm3" },
#else
	{ (unsigned char *) "«Q§f¹ğ¼i®ÈÁ\\»MÁ¹¾T", (unsigned char *) "xm3" },
#endif  /*WIN32*/
	{ (unsigned char *) "«ß¼{Âo²vºñ", (unsigned char *) "xm4" },
	{ (unsigned char *) "Ãq¾[Æj", (unsigned char *) "xm6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ÂS½U¦ÔÁ¢", (unsigned char *) "xo3" },
#ifdef  WIN32
	{ (unsigned char *) "²Ö²\Ãş", (unsigned char *) "xo4" },
#else
	{ (unsigned char *) "²Ö²\\Ãş", (unsigned char *) "xo4" },
#endif  /*WIN32*/
	{ (unsigned char *) "¹p¹ã¾İÁ]Ã½ÅJ", (unsigned char *) "xo6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "«¨", (unsigned char *) "xu, " },
	{ (unsigned char *) "¯P¨æ¦C¦H±Ê¬{ÂyµõÆc", (unsigned char *) "xu,4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¬h¹g", (unsigned char *) "xu.3" },
	{ (unsigned char *) "¤»·ÈÂüÃH", (unsigned char *) "xu.4" },
	{ (unsigned char *) "¼Bºh¬yÂs¯[¯d½F²¸»¿", (unsigned char *) "xu.6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "©ğ", (unsigned char *) "xu/ " },
	{ (unsigned char *) "À­»â", (unsigned char *) "xu/3" },
	{ (unsigned char *) "¥t¥O", (unsigned char *) "xu/4" },
	{ (unsigned char *) "§D¹a­â¬SÄçª~¬Âºğ²Ü²Ş²â­dµÙ³M³®¹s½·ÆFÀoÄÖ", (unsigned char *) "xu/6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "Áy", (unsigned char *) "xu03" },
	{ (unsigned char *) "ÅÊÀÄ·¯ÀÔÄk·Ò½mÁåÃì", (unsigned char *) "xu04" },
	{ (unsigned char *) "³s·G¼¦½¬¹İ©©º§¾üÃ®ÅIÅ¿Áp", (unsigned char *) "xu06" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "§õ­ù«Z®[¿C¯@²zÂ§ÃU¸Ì¨½", (unsigned char *) "xu3" },
	{ (unsigned char *) "¥ß¤O¨Ò«WÄ×§QÀy¼F¥{¦O°æÃc·X©Ñ¾ä®ßÅÏ¾ú·ÌÃwµgÂ~ÄrÄt²Á²É¯ïÄ÷Å°ÁõÆE°¬ÄR²ú»Y", (unsigned char *) "xu4" },
	{ (unsigned char *) "³í±ù²|ºv²p¼ù¯W¼şÆX¿©¸ÄÄù¾¤»©ÂçÂ÷", (unsigned char *) "xu6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¨â­ÇÃR", (unsigned char *) "xu;3" },
	{ (unsigned char *) "´½½Ì½ø«G", (unsigned char *) "xu;4" },
	{ (unsigned char *) "¨}±çÂ³¼Ù²D¸d¶q", (unsigned char *) "xu;6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤F¾éÁA", (unsigned char *) "xul3" },
	{ (unsigned char *) "®Æ¹ù", (unsigned char *) "xul4" },
	{ (unsigned char *) "¹±¹é¼d¼º¼ã¿RÀøÂ·²á¿ñ¼I", (unsigned char *) "xul6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "»ş¾Ï", (unsigned char *) "xup3" },
	{ (unsigned char *) "Ä©¸îÆn", (unsigned char *) "xup4" },
	{ (unsigned char *) "ªL²O¿MµY¿Z·÷ÁCÁ{Ãá¿î¾FÀMÅìÅï", (unsigned char *) "xup6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¹QÁİ³µ", (unsigned char *) "y. " },
	{ (unsigned char *) "¨«", (unsigned char *) "y.3" },
	{ (unsigned char *) "«µ´~ÆJ", (unsigned char *) "y.4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¼W¼¨Â¹", (unsigned char *) "y/ " },
	{ (unsigned char *) "ÃØ", (unsigned char *) "y/4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ÃÙÅĞÆg", (unsigned char *) "y04" },
	{ (unsigned char *) "°¯", (unsigned char *) "y06" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¸ê«t«º§¶²d´F´şºı¯÷¿Ô¸í½ıÀEÀhÅh", (unsigned char *) "y " },
	{ (unsigned char *) "¤l¥J±ê·º¬óµµ¸ä", (unsigned char *) "y3" },
	{ (unsigned char *) "¦r¦Û®¡º{", (unsigned char *) "y4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "²Ï¥`", (unsigned char *) "y8 " },
	{ (unsigned char *) "«¥¯{Âø", (unsigned char *) "y86" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "«v®â¨a", (unsigned char *) "y9 " },
	{ (unsigned char *) "®_", (unsigned char *) "y93" },
	{ (unsigned char *) "¦A¦b¸ü", (unsigned char *) "y94" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ÅØ»NÅBÅ¼", (unsigned char *) "y; " },
	{ (unsigned char *) "®NÅ¦¸®ÂÃ", (unsigned char *) "y;4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "©v´ÄÂÜÃO", (unsigned char *) "yj/ " },
	{ (unsigned char *) "¶Í", (unsigned char *) "yj/3" },
	{ (unsigned char *) "Áaºêºî", (unsigned char *) "yj/4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "Ä¡", (unsigned char *) "yj03" },
	{ (unsigned char *) "Æp÷İ", (unsigned char *) "yj04" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¯²", (unsigned char *) "yj " },
	{ (unsigned char *) "²Õ«[¯ª¶Aªı", (unsigned char *) "yj3" },
	{ (unsigned char *) "¨ò±Ú¨¬", (unsigned char *) "yj6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¦õ¥ª", (unsigned char *) "yji3" },
	{ (unsigned char *) "§@°µ§¤®y¬g¯®", (unsigned char *) "yji4" },
	{ (unsigned char *) "¬Q", (unsigned char *) "yji6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¼L", (unsigned char *) "yjo3" },
	{ (unsigned char *) "³Ì¸o¿¿¾K", (unsigned char *) "yjo4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "´L¾ê¿í", (unsigned char *) "yjp " },
	{ (unsigned char *) "¼Á", (unsigned char *) "yjp3" },
	{ (unsigned char *) "¦`", (unsigned char *) "yjp4" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤·", (unsigned char *) "yk4" },
	{ (unsigned char *) "«h¹É¾Ü¿A²È³d", (unsigned char *) "yk6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ÁV¾D", (unsigned char *) "yl " },
	{ (unsigned char *) "¦­´Ç¾şÄ¦°D", (unsigned char *) "yl3" },
	{ (unsigned char *) "³y¨m¾¸¨_ÀêÄ·Ä¼", (unsigned char *) "yl4" },
	{ (unsigned char *) "Æw", (unsigned char *) "yl6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¸é", (unsigned char *) "yo6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "«ç", (unsigned char *) "yk3" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "ªæ", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "§_¦Î", (unsigned char *) "z.3" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤¥«Ê®p·¬²lºÆ¸ÁÂ×¾W­·", (unsigned char *) "z/ " },
	{ (unsigned char *) "©^­Ä»ñ¿Ø", (unsigned char *) "z/4" },
	{ (unsigned char *) "Á_³{¶¾", (unsigned char *) "z/6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¿»¼nµfÂºÂ½", (unsigned char *) "z0 " },
	{ (unsigned char *) "¤Ïªğ", (unsigned char *) "z03" },
	{ (unsigned char *) "½d¶º±ë¥Æ¦Æªx¥Ç­S³c", (unsigned char *) "z04" },
#ifdef  WIN32
	{ (unsigned char *) "¤Z¼\¦|¼Ô·ĞÄsÁcÃ¿³«", (unsigned char *) "z06" },
#else
	{ (unsigned char *) "¤Z¼\\¦|¼Ô·ĞÄsÁcÃ¿³«", (unsigned char *) "z06" },
#endif  /*WIN32*/
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "µo¥ï", (unsigned char *) "z8 " },
	{ (unsigned char *) "ªk¾v", (unsigned char *) "z83" },
	{ (unsigned char *) "µW", (unsigned char *) "z84" },
	{ (unsigned char *) "¥F¯|µ­»@»Ö", (unsigned char *) "z86" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤è§{ªDªÚ", (unsigned char *) "z; " },
	{ (unsigned char *) "¥é­À§Ï¯¼¯é³X", (unsigned char *) "z;3" },
	{ (unsigned char *) "©ñ", (unsigned char *) "z;4" },
	{ (unsigned char *) "¨¾©Ğ§«ªÕ", (unsigned char *) "z;6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤Ò¥í¹å¼Å½§³l¾¢¶y", (unsigned char *) "zj " },
	{ (unsigned char *) "­Á©²¼¾©ò¨j»GµÆ³@»²°y¾f", (unsigned char *) "zj3" },
	{ (unsigned char *) "¥I³Å°Æ©J°ü´I´_¤÷¸¡½ÆÂĞ­r­t½áÁÌ­uªúªşÃL¾t", (unsigned char *) "zj4" },
	{ (unsigned char *) "ªA¥ñ«R°Ë§·´T¥±©»©Ì§ß©Ø¬t¯B²eºÖ²Å²Ù²Ñ¿£ªÜµè½»µö¿ç", (unsigned char *) "zj6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "«D°Ø¦m´vµáÀP­¸", (unsigned char *) "zo " },
	{ (unsigned char *) "­ê´´»B½Ú", (unsigned char *) "zo3" },
	{ (unsigned char *) "¼o¶O§p±Qªm·óªÍªè", (unsigned char *) "zo4" },
	{ (unsigned char *) "ªÎµÌ", (unsigned char *) "zo6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "¤À§h´Ùª^¯Éªâ", (unsigned char *) "zp " },
	{ (unsigned char *) "¯»", (unsigned char *) "zp3" },
	{ (unsigned char *) "¥÷¾Ä©Á¼«ÁT", (unsigned char *) "zp4" },
	{ (unsigned char *) "¼X¨WµI", (unsigned char *) "zp6" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) "", (unsigned char *) "" },
	{ (unsigned char *) 0, (unsigned char *) 0 } };
